# Arenda.az Data Collection & Preparation Report

This notebook builds a property dataset for multimodal modeling.

## Workflow at a glance
1. Collect listing URLs
2. Scrape tabular property features
3. Download listing images
4. Merge and clean all batch outputs

In [2]:
from tqdm import tqdm
import pandas as pd
import requests
from bs4 import BeautifulSoup
import regex as re
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.chrome.service import Service
import urllib.request
import numpy as np
from selenium.webdriver.chrome.options import Options
import os
from pathlib import Path
from urllib.parse import urlparse

## 1) Environment Setup
Load required scraping, parsing, and utility libraries.

In [ ]:
# Setup Chrome options

chrome_options = Options()
chrome_options.add_argument('--disable-blink-features=AutomationControlled')
chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
chrome_options.add_experimental_option('useAutomationExtension', False)
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36')

# Use ChromeDriverManager
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service, options=chrome_options)

# Anti-detection
driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")

url = 'https://arenda.az/filtirli-axtaris/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max='
driver.get(url)

time.sleep(3)

## 2) Listing URL Discovery
Open filtered search pages, parse HTML, and collect unique `satilir` listing links.

**Output:** `satilir_links.csv`

In [3]:
# Get page source from Selenium driver instead of requests
page_source = driver.page_source
bs = BeautifulSoup(page_source, 'html.parser')

In [4]:
bs

<html class="html_az" id="html" lang="az"><head><script async="" src="https://st.top100.ru/top100/3.18.16/mgc.js" type="text/javascript"></script><script async="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-EXGHL2Q2LY&amp;cx=c&amp;_slc=1" type="text/javascript"></script><script async="" src="https://st.top100.ru/top100/top100.js" type="text/javascript"></script><script async="" src="//www.google-analytics.com/analytics.js"></script> <meta charset="utf-8"/> <link href="https://arenda.az/public/css/img/favicon.png" rel="shortcut icon"/> <link href="https://arenda.az/public/css/img/favicon.png" rel="apple-touch-icon-precomposed"/> <meta content="37fb16dcf3d065c2" name="yandex-verification"/> <!-- Title --> <title> Ətraflı axtarış </title> <link crossorigin="anonymous" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" referrerpolicy="no-referrer" rel="stylesheet"/> <link href="https://cdn.jsdelivr.net/npm/@mdi/font@7.4.47/css/materialdesignicons.min.css" rel="stylesheet"/> <!-- Google Tag Manager --> <script async="" src="https://connect.facebook.net/signals/config/894945628285912?v=2.9.300&amp;r=stable&amp;domain=arenda.az&amp;hme=c048e760b3fdc0fbdc117d7607b2c36e13eff2660c515ac72e86dac5ba060bb9&amp;ex_m=104%2C205%2C154%2C22%2C72%2C73%2C145%2C68%2C67%2C11%2C162%2C90%2C16%2C138%2C127%2C39%2C75%2C78%2C134%2C159%2C164%2C8%2C4%2C5%2C7%2C6%2C3%2C91%2C101%2C165%2C170%2C219%2C62%2C186%2C187%2C55%2C277%2C30%2C74%2C231%2C230%2C229%2C23%2C33%2C103%2C61%2C10%2C63%2C97%2C98%2C99%2C105%2C130%2C31%2C29%2C132%2C133%2C129%2C128%2C155%2C76%2C158%2C156%2C157%2C50%2C60%2C123%2C15%2C161%2C45%2C264%2C265%2C263%2C26%2C27%2C28%2C48%2C146%2C77%2C112%2C18%2C20%2C44%2C40%2C42%2C41%2C83%2C92%2C96%2C110%2C144%2C147%2C46%2C111%2C24%2C21%2C119%2C69%2C36%2C149%2C148%2C150%2C141%2C139%2C25%2C35%2C59%2C109%2C160%2C70%2C17%2C152%2C114%2C81%2C66%2C19%2C85%2C86%2C116%2C84%2C136%2C135%2C34%2C279%2C294%2C212%2C201%2C202%2C200%2C297%2C289%2C52%2C213%2C107%2C131%2C80%2C121%2C54%2C47%2C49%2C113%2C120%2C126%2C58%2C64%2C151%2C115%2C37%2C32%2C53%2C56%2C100%2C163%2C1%2C124%2C14%2C122%2C12%2C2%2C57%2C93%2C65%2C118%2C89%2C88%2C166%2C167%2C94%2C95%2C9%2C125%2C102%2C51%2C142%2C87%2C79%2C71%2C117%2C106%2C43%2C143%2C0%2C82%2C137%2C140%2C153%2C38%2C108%2C13%2C168%2C228%2C227%2C222%2C224%2C225%2C226%2C223%2C211%2C221%2C193%2C190%2C191%2C185%2C189%2C192%2C188%2C183%2C317%2C196%2C215%2C184%2C182%2C235%2C206%2C176%2C177%2C172%2C178%2C175%2C173%2C174%2C171%2C169%2C180%2C181%2C179%2C266%2C316%2C194%2C238%2C239%2C244%2C241%2C243%2C242%2C240%2C237%2C252%2C248%2C249%2C247%2C253%2C250%2C246%2C251%2C245"></script><script async="" src="https://connect.facebook.net/signals/config/3492205447716263?v=2.9.300&amp;r=stable&amp;domain=arenda.az&amp;hme=c048e760b3fdc0fbdc117d7607b2c36e13eff2660c515ac72e86dac5ba060bb9&amp;ex_m=104%2C205%2C154%2C22%2C72%2C73%2C145%2C68%2C67%2C11%2C162%2C90%2C16%2C138%2C127%2C39%2C75%2C78%2C134%2C159%2C164%2C8%2C4%2C5%2C7%2C6%2C3%2C91%2C101%2C165%2C170%2C219%2C62%2C186%2C187%2C55%2C277%2C30%2C74%2C231%2C230%2C229%2C23%2C33%2C103%2C61%2C10%2C63%2C97%2C98%2C99%2C105%2C130%2C31%2C29%2C132%2C133%2C129%2C128%2C155%2C76%2C158%2C156%2C157%2C50%2C60%2C123%2C15%2C161%2C45%2C264%2C265%2C263%2C26%2C27%2C28%2C48%2C146%2C77%2C112%2C18%2C20%2C44%2C40%2C42%2C41%2C83%2C92%2C96%2C110%2C144%2C147%2C46%2C111%2C24%2C21%2C119%2C69%2C36%2C149%2C148%2C150%2C141%2C139%2C25%2C35%2C59%2C109%2C160%2C70%2C17%2C152%2C114%2C81%2C66%2C19%2C85%2C86%2C116%2C84%2C136%2C135%2C34%2C279%2C294%2C212%2C201%2C202%2C200%2C297%2C289%2C52%2C213%2C107%2C131%2C80%2C121%2C54%2C47%2C49%2C113%2C120%2C126%2C58%2C64%2C151%2C115%2C37%2C32%2C53%2C56%2C100%2C163%2C1%2C124%2C14%2C122%2C12%2C2%2C57%2C93%2C65%2C118%2C89%2C88%2C166%2C167%2C94%2C95%2C9%2C125%2C102%2C51%2C142%2C87%2C79%2C71%2C117%2C106%2C43%2C143%2C0%2C82%2C137%2C140%2C153%2C38%2C108%2C13%2C168"></script><script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script><script async="" src="https://www.googletagmanager.com/gtm.js?id=GTM-T5NMWWP"></script><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-T5NMWWP');</script> <!-- End Google Tag Manager --> <!-- Meta Pixel Code --> <script> !function(f,b,e,v,n,t,s) {if(f.fbq)return;n=f.fbq=function(){n.callMethod? n.callMethod.apply(n,arguments):n.queue.push(arguments)}; if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0'; n.queue=[];t=b.createElement(e);t.async=!0; t.src=v;s=b.getElementsByTagName(e)[0]; s.parentNode.insertBefore(t,s)}(window, document,'script', 'https://connect.facebook.net/en_US/fbevents.js'); fbq('init', '3492205447716263'); fbq('track', 'PageView'); </script> <noscript><img height="1" src="https://www.facebook.com/tr?id=3492205447716263&amp;ev=PageView&amp;noscript=1" style="display:none" width="1"/></noscript> <!-- End Meta Pixel Code --> <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/> <meta content="1300" name="viewport"/> <meta content="True" name="HandheldFriendly"/> <meta content="telephone=yes" name="format-detection"/> <meta content="az" property="og:locale"/> <meta content="az" http-equiv="Content-Language"/> <link href="https://arenda.az/filtirli-axtaris" hreflang="az-az" rel="alternate"/> <meta content="notranslate" name="google"/> <meta content="all, index, follow" name="robots"/> <meta content="all, index, follow" name="googlebot"/> <meta content="Dasinmaz emlak ve ev alqi satqisi, ev elanlari 2018, dasinmaz emlak elanlari| Ev elanlari - Dasinmaz emlak , bina, ofis ve villalar və bag evleri | evler ve menziller ve ev alqi-satqisini Arenda.az -da. Bizde evlerin satisi yanasi diger obyektlerin al" name="description"/> <meta content="arenda,kiraye,evler,bina,ofis,Kiraye evler,villalar,bag evleri,kiraye masinlar,rent a car,gelinlik kirayesi,kiraye paltar,prokat,evlerin kirayesi,sutkaliq evler,gundelik evler,gunluk evler,gelinlik paltarlari,toy masinlari" name="keywords"/> <noscript> <meta content="0;url=noJs.html" http-equiv="refresh"/> </noscript> <meta content="2016-08-23 03:20:55" property="article:published_time"/> <meta content="" property="article:author"/> <meta content="article" property="og:type"/> <meta content="https://arenda.az/filtirli-axtaris" property="og:url"/> <meta content="Ətraflı axtarış" property="og:title"/> <meta content="https://arenda.az/public/css/img/arenda_share.png" property="og:image"/> <meta content="Dasinmaz emlak ve ev alqi satqisi, ev elanlari 2018, dasinmaz emlak elanlari| Ev elanlari - Dasinmaz emlak , bina, ofis ve villalar və bag evleri | evler ve menziller ve ev alqi-satqisini Arenda.az -da. Bizde evlerin satisi yanasi diger obyektlerin al" property="og:description"/> <meta content="Arenda.az- dasinmaz emlak və ev alqi satqisi, ev elanlari 2021, dasinmaz emlak elanlari" property="og:site_name"/> <meta content="https://arenda.az/filtirli-axtaris" name="twitter:site"/> <meta content="Ətraflı axtarış" name="twitter:title"/> <meta content="Dasinmaz emlak ve ev alqi satqisi, ev elanlari 2018, dasinmaz emlak elanlari| Ev elanlari - Dasinmaz emlak , bina, ofis ve villalar və bag evleri | evler ve menziller ve ev alqi-satqisini Arenda.az -da. Bizde evlerin satisi yanasi diger obyektlerin al" name="twitter:description"/> <meta content="https://arenda.az/public/css/img/arenda_share.png" name="twitter:image"/> <script>var BASE_URL='https://arenda.az'; const IS_MOBILE=''; const IS_MOBILE_DEVICE=''; const VERSION=''; const MEDIA_SOURCE='https://arenda.az/';</script> <link href="https://arenda.az/filtirli-axtaris/2/?home_search=1&amp;lang=1&amp;site=1&amp;home_s=1&amp;elan_novu%5B1%5D=1&amp;emlak_novu%5B370%5D=370&amp;emlak_novu%5B371%5D=371&amp;emlak_novu%5B5%5D=5&amp;emlak_novu%5B861%5D=861&amp;price_min=&amp;price_max=&amp;axtar=&amp;sahe_min=&amp;sahe_max=&amp;mertebe_min=&amp;mertebe_max=&amp;y_mertebe_min=&amp;y_mertebe_max=" id="next" rel="next"/><link href="https://arenda.az/public/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css"/><link href="https://arenda.az/public/css/main.desktop.css?v=17042026-1730" rel="stylesheet" type="text/css"/><script> var loadDeferredStyles = function () { var addStylesNode = document.getElementById('deferred-styles'); var replacement = document.createElement('div'); replacement.innerHTML = addStylesNode.textContent; document.body.appendChild(replacement); addStylesNode.parentElement.removeChild(addStylesNode); }; var raf = requestAnimationFrame || mozRequestAnimationFrame || webkitRequestAnimationFrame || msRequestAnimationFrame; if (raf) raf(function () { window.setTimeout(loadDeferredStyles, 0); }); else window.addEventListener('load', loadDeferredStyles);</script><script src="https://arenda.az/public/js/main.combine.js?v=1.2"></script><script> var fancybox_opt = { openEffect	: 'none', closeEffect	: 'none', prevEffect	: 'none', nextEffect	: 'none', margin: 0, padding:0, maxWidth: '100%', maxHeight: '100%', autoSize: true, autoResize: true, aspectRatio: true, helpers: { overlay: { locked: true } } }; var teklif_opt = { modal: true, openEffect	: 'none', closeEffect	: 'none', prevEffect	: 'none', nextEffect	: 'none', margin: 0, padding:0, maxWidth: '90%', maxHeight: '90%', autoSize: true, autoResize: true, aspectRatio: true, helpers: { overlay: { locked: false } }, closeClick: true, hideOnOverlayClick:false, hideOnContentClick:false };</script><script defer="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script> <script src="https://content.adriver.ru/adriver.core.2.js" type="text/javascript"></script> <script defer="" src="https://cdn.jsdelivr.net/npm/@alpinejs/intersect@3.x.x/dist/cdn.min.js"></script> <script defer="" src="https://cdn.jsdelivr.net/npm/@alpinejs/collapse@3.x.x/dist/cdn.min.js"></script> <script defer="" src="https://cdn.jsdelivr.net/npm/@alpinejs/mask@3.x.x/dist/cdn.min.js"></script> <script defer="" src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script><meta content="AlK2UR5SkAlj8jjdEc9p3F3xuFYlF6LYjAML3EOqw1g26eCwWPjdmecULvBH5MVPoqKYrOfPhYVL71xAXI1IBQoAAAB8eyJvcmlnaW4iOiJodHRwczovL2RvdWJsZWNsaWNrLm5ldDo0NDMiLCJmZWF0dXJlIjoiV2ViVmlld1hSZXF1ZXN0ZWRXaXRoRGVwcmVjYXRpb24iLCJleHBpcnkiOjE3NTgwNjcxOTksImlzU3ViZG9tYWluIjp0cnVlfQ==" http-equiv="origin-trial"/><meta content="Amm8/NmvvQfhwCib6I7ZsmUxiSCfOxWxHayJwyU1r3gRIItzr7bNQid6O8ZYaE1GSQTa69WwhPC9flq/oYkRBwsAAACCeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZXN5bmRpY2F0aW9uLmNvbTo0NDMiLCJmZWF0dXJlIjoiV2ViVmlld1hSZXF1ZXN0ZWRXaXRoRGVwcmVjYXRpb24iLCJleHBpcnkiOjE3NTgwNjcxOTksImlzU3ViZG9tYWluIjp0cnVlfQ==" http-equiv="origin-trial"/><meta content="A9nrunKdU5m96PSN1XsSGr3qOP0lvPFUB2AiAylCDlN5DTl17uDFkpQuHj1AFtgWLxpLaiBZuhrtb2WOu7ofHwEAAACKeyJvcmlnaW4iOiJodHRwczovL2RvdWJsZWNsaWNrLm5ldDo0NDMiLCJmZWF0dXJlIjoiQUlQcm9tcHRBUElNdWx0aW1vZGFsSW5wdXQiLCJleHBpcnkiOjE3NzQzMTA0MDAsImlzU3ViZG9tYWluIjp0cnVlLCJpc1RoaXJkUGFydHkiOnRydWV9" http-equiv="origin-trial"/><meta content="A93bovR+QVXNx2/38qDbmeYYf1wdte9EO37K9eMq3r+541qo0byhYU899BhPB7Cv9QqD7wIbR1B6OAc9kEfYCA4AAACQeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZXN5bmRpY2F0aW9uLmNvbTo0NDMiLCJmZWF0dXJlIjoiQUlQcm9tcHRBUElNdWx0aW1vZGFsSW5wdXQiLCJleHBpcnkiOjE3NzQzMTA0MDAsImlzU3ViZG9tYWluIjp0cnVlLCJpc1RoaXJkUGFydHkiOnRydWV9" http-equiv="origin-trial"/><meta content="A1S5fojrAunSDrFbD8OfGmFHdRFZymSM/1ss3G+NEttCLfHkXvlcF6LGLH8Mo5PakLO1sCASXU1/gQf6XGuTBgwAAACQeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZXRhZ3NlcnZpY2VzLmNvbTo0NDMiLCJmZWF0dXJlIjoiQUlQcm9tcHRBUElNdWx0aW1vZGFsSW5wdXQiLCJleHBpcnkiOjE3NzQzMTA0MDAsImlzU3ViZG9tYWluIjp0cnVlLCJpc1RoaXJkUGFydHkiOnRydWV9" http-equiv="origin-trial"/><style type="text/css">.fancybox-margin{margin-right:15px;}</style></head><body class="center2 desktop_body page_80" ng-app="arenda" ng-controller="ngCtrl"> <script> fbq('track', 'Lead'); fbq('track', 'Search'); fbq('track', 'ViewContent'); </script> <!-- Global site tag (gtag.js) - Google Analytics --> <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-83317925-1"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'UA-83317925-1'); (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','//www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-83317925-1', 'auto'); ga('send', 'pageview'); </script> <div id="fb-root"></div><header class="full header"> <section class="center" id=""> <section class="full top_section full-height px-3"> <div class="pos_rel float-left full-height"> <ul class="pos_rel float-left soc_list translateY"> <li><a class="fb" href="https://www.facebook.com/arenda.az" target="_blank"> <svg fill="#FFF" version="1.1" viewbox="0 0 80 80" width="16" xmlns="http://www.w3.org/2000/svg"> <g> <g id="Layer_1"> <path d="M46.95,80v-35h11.67l2.22-14.48h-13.89v-9.4c0-3.96,1.94-7.82,8.16-7.82h6.32V.98s-5.73-.98-11.21-.98c-11.44,0-18.92,6.93-18.92,19.49v11.04h-12.72v14.48h12.72v35h15.65Z"></path> </g> </g> </svg> </a> </li> <li><a class="ins" href="https://www.instagram.com/arenda.az/" target="_blank"> <svg fill="#FFF" version="1.1" viewbox="0 0 80 80" width="16" xmlns="http://www.w3.org/2000/svg"> <g> <g id="Layer_1"> <g> <path d="M61.18,14.28c-2.59,0-4.69,2.1-4.69,4.69s2.1,4.69,4.69,4.69,4.69-2.1,4.69-4.69-2.1-4.69-4.69-4.69Z"></path> <path d="M40.33,20.3c-10.86,0-19.7,8.84-19.7,19.7s8.84,19.7,19.7,19.7,19.7-8.84,19.7-19.7-8.84-19.7-19.7-19.7ZM40.33,52.62c-6.96,0-12.62-5.66-12.62-12.62s5.66-12.62,12.62-12.62,12.62,5.66,12.62,12.62-5.66,12.62-12.62,12.62Z"></path> <path d="M55.97,80h-31.94C10.78,80,0,69.22,0,55.97v-31.94C0,10.78,10.78,0,24.03,0h31.94c13.25,0,24.03,10.78,24.03,24.03v31.94c0,13.25-10.78,24.03-24.03,24.03ZM24.03,7.53c-9.1,0-16.5,7.4-16.5,16.5v31.94c0,9.1,7.4,16.5,16.5,16.5h31.94c9.1,0,16.5-7.4,16.5-16.5v-31.94c0-9.1-7.4-16.5-16.5-16.5h-31.94Z"></path> </g> </g> </g> </svg> </a> </li> <li><a class="yt" href="https://www.youtube.com/channel/UCZFYL3miTL_Eq9jBGfEw_qQ" target="_blank"> <svg fill="#FFF" version="1.1" viewbox="0 0 80 80" xmlns="http://www.w3.org/2000/svg"> <g> <g> <g> <path d="M60.92,11.19H19.08C8.56,11.19,0,19.74,0,30.27v19.47c0,10.52,8.56,19.08,19.08,19.08h41.85c10.52,0,19.08-8.56,19.08-19.08v-19.47c0-10.52-8.56-19.08-19.08-19.08ZM74.57,30.27v19.47c0,7.53-6.12,13.65-13.65,13.65H19.08c-7.53,0-13.65-6.12-13.65-13.65v-19.47c0-7.53,6.12-13.65,13.65-13.65h41.85c7.53,0,13.65,6.12,13.65,13.65Z"></path> <path d="M53.2,37.15l-17.92-9.75c-1.67-.95-4.25-.35-5.47.35-1.66.97-1.84,2.4-1.84,2.97v19.06c0,.56.17,1.97,1.8,2.94.75.45,2.1.9,3.42.9.76,0,1.41-.15,1.94-.43l18.69-9.25h0s.29-.14.29-.14h0c.99-.6,1.59-1.63,1.6-2.77.02-1.78-1.33-3.19-2.5-3.86ZM48.2,40.65l-14.81,7.33v-15.43l14.81,8.09Z "></path> </g> </g> </g> </svg> </a> </li> <li><a class="tiktok" href="https://www.tiktok.com/@arenda.az" target="_blank"> <svg fill="#FFF" version="1.1" viewbox="0 0 80 80" width="16" xmlns="http://www.w3.org/2000/svg"> <g> <g id="Layer_1"> <path class="cls-1" d="M74.22,32.37c-.65.06-1.31.1-1.97.1-7.2,0-13.92-3.63-17.87-9.66v32.89c0,13.42-10.88,24.31-24.31,24.31s-24.31-10.88-24.31-24.31,10.88-24.31,24.31-24.31h0c.51,0,1,.05,1.5.08v11.98c-.5-.06-.99-.15-1.5-.15-6.85,0-12.4,5.55-12.4,12.41s5.55,12.41,12.4,12.41,12.9-5.4,12.9-12.25l.12-55.85h11.46c1.08,10.28,9.37,18.3,19.67,19.05v13.31"></path> </g> </g> </svg> </a> </li> <li> <a class="whatsapp" href="https://wa.me/+994705962424" target="_blank"> <svg fill="#FFF" version="1.1" viewbox="0 0 80 80" width="16" xmlns="http://www.w3.org/2000/svg"> <g> <g id="Layer_1"> <g> <path d="M.1,80l5.74-21.4c-3.25-5.86-4.96-12.42-4.96-19.09C.88,17.73,18.6,0,40.39,0s39.51,17.73,39.51,39.51-17.73,39.51-39.51,39.51c-6.54,0-13-1.65-18.78-4.79L.1,80ZM22.68,66.22l1.35.81c4.97,2.96,10.63,4.53,16.36,4.53,17.67,0,32.04-14.37,32.04-32.04S58.06,7.47,40.39,7.47,8.35,21.84,8.35,39.51c0,5.83,1.62,11.58,4.69,16.61l.83,1.36-3.2,11.95,12.02-3.22Z" fill-rule="evenodd"></path> <path d="M55.09,45.01c-1.63-.97-3.74-2.06-5.66-1.27-1.47.6-2.41,2.9-3.36,4.08-.49.6-1.07.7-1.82.4-5.52-2.2-9.75-5.88-12.79-10.96-.52-.79-.42-1.41.2-2.14.92-1.08,2.07-2.31,2.32-3.77.25-1.46-.44-3.17-1.04-4.46-.77-1.66-1.63-4.03-3.3-4.97-1.53-.86-3.54-.38-4.91.73-2.35,1.91-3.49,4.91-3.45,7.89,0,.84.11,1.69.31,2.5.47,1.96,1.38,3.79,2.4,5.53.77,1.31,1.61,2.59,2.51,3.81,2.95,4.01,6.62,7.49,10.87,10.1,2.12,1.3,4.41,2.44,6.78,3.22,2.66.88,5.02,1.79,7.89,1.25,3-.57,5.97-2.43,7.16-5.32.35-.86.53-1.81.33-2.72-.41-1.87-2.94-2.98-4.46-3.89Z"></path> </g> </g> </g> </svg> </a> </li> </ul> <ul class="lang_list pos_rel float-left translateY"> <li> <img alt="azeri" src="https://arenda.az/public/css/img/aze.png"/> <button class="lang_arrow text-white" type="button"> <i class="fa-solid fa-chevron-down"></i> </button> <ul class="sub_lang"> <li> <a href="https://arenda.az/ru/rasshirennyy-poisk/?home_search=1&amp;lang=1&amp;site=1&amp;home_s=1&amp;elan_novu%5B1%5D=1&amp;emlak_novu%5B370%5D=370&amp;emlak_novu%5B371%5D=371&amp;emlak_novu%5B5%5D=5&amp;emlak_novu%5B861%5D=861&amp;price_min=&amp;price_max=&amp;axtar=&amp;sahe_min=&amp;sahe_max=&amp;mertebe_min=&amp;mertebe_max=&amp;y_mertebe_min=&amp;y_mertebe_max="> <img alt="russian" src="https://arenda.az/public/css/img/ru.png"/> </a> </li> </ul> </li> </ul> </div> <div class="pos_rel float-right full-height top_right d-flex flex-nowrap align-items-center"> <nav class="nav web_menu_nav translateY pos_rel float-left h-100"> <ul class="menu web_menu_list pos_rel float-left 111 d-flex align-items-center"> <li> <a class="active_menu" href="https://arenda.az/xeberler" title="Xəbərlər"> Xəbərlər </a></li><li> <a class="" href="https://arenda.az/dasinmaz-emlak-agentlikleri" title="Agentliklər"> Agentliklər </a></li><li> <a class="" href="https://arenda.az/yasayis-kompleksi" title="Yaşayış Kompeksləri"> Yaşayış Kompeksləri </a></li><li> <a class="" href="https://arenda.az/istifadecilerin-reytinqi" title="İstifadəçi Reytinqi"> İstifadəçi Reytinqi </a></li> </ul> </nav> <a class="wp_tel h-100 pos_rel float-left translateY d-flex align-items-center" href="tel:+994 70 596 24 24"> <img alt="" class="mr-1" src="https://arenda.az/public/images/phone-white-12.svg?v=1"/> +994 70 596 24 24 </a> <div class="search_box pos_rel float-left translateY h-100"> <form action="https://arenda.az/kodla-axtaris/" autocomplete="on" class="full full-height d-flex align-items-center" method="get"> <div> <input class="search_by_code_input" name="s_elan" placeholder="Kodla, sözlə axtarış" type="search"/> <button class="search_by_code_btn translateY d-flex" type="submit"> <svg fill="#FFF" version="1.1" viewbox="0 0 80 80" width="19" xmlns="http://www.w3.org/2000/svg"> <g> <g id="Layer_1"> <g> <path d="M27.97,10.81c-8.86,1.4-15.75,8.3-17.15,17.16-.13.8.07,1.6.54,2.26s1.18,1.09,1.98,1.21c.16.03.32.04.48.04.63,0,1.25-.2,1.78-.58.66-.48,1.09-1.18,1.21-1.98.99-6.25,5.86-11.12,12.11-12.11.8-.13,1.5-.56,1.98-1.21s.67-1.46.54-2.26-.56-1.51-1.21-1.98-1.47-.68-2.26-.54Z"></path> <path d="M34.72,0C15.57,0,0,15.57,0,34.72s15.57,34.72,34.72,34.72,34.72-15.57,34.72-34.72S53.86,0,34.72,0ZM63.37,34.72c0,15.8-12.85,28.65-28.65,28.65S6.07,50.52,6.07,34.72,18.92,6.07,34.72,6.07s28.65,12.85,28.65,28.65Z"></path> <path d="M79.11,74.82l-14.08-14.08c-1.18-1.19-3.11-1.19-4.29,0-.57.57-.89,1.33-.89,2.15s.32,1.57.89,2.14l14.08,14.08c.59.6,1.37.89,2.15.89s1.55-.29,2.15-.89c1.18-1.18,1.18-3.11,0-4.29Z"></path> </g> </g> </g> </svg> </button> </div> </form> </div> </div> </section> <sec

In [5]:
# Extract all href links
links = []
for a_tag in bs.find_all('a', href=True):
    links.append(a_tag['href'])

# Display unique links
print(f"Total links found: {len(links)}")
print(f"Unique links: {len(set(links))}")
print("\nFirst 10 links:")
for link in links:
    print(link)

Total links found: 143
Unique links: 120

First 10 links:
https://www.facebook.com/arenda.az
https://www.instagram.com/arenda.az/
https://www.youtube.com/channel/UCZFYL3miTL_Eq9jBGfEw_qQ
https://www.tiktok.com/@arenda.az
https://wa.me/+994705962424
https://arenda.az/ru/rasshirennyy-poisk/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max=
https://arenda.az/xeberler
https://arenda.az/dasinmaz-emlak-agentlikleri
https://arenda.az/yasayis-kompleksi
https://arenda.az/istifadecilerin-reytinqi
tel:+994 70 596 24 24
https://arenda.az/
https://arenda.az/secilmisler
#login_box
#register_box
https://arenda.az/elan-yerlesdir
https://yigim.az/
https://yigim.az/
#premium_et
https://arenda.az/satilir-3-otaqli-yeni-tikili-bineqedi-rayonu-nesimi-metrosu-9-cu-mikrorayon-mir-celal-137a-4
https://arenda.az/satilir-5-otaqli-yeni-tikili-xetai-rayonu-xetai-metrosu-baki-seheri-xetai-rayonu
https://arenda.az/satilir-4-otaqli-heyet-evi-villa-abseron-rayonu-masazir-eliaga-vahid-kuc-595
https://arenda.az/satilir-3-otaqli-yeni-tikili-nerimanov-rayonu-neriman-nerimanov-metrosu-montin-qes-nerimanov-rayonu-mayakovski-kucesi
https://arenda.az/satilir-1-otaqli-yeni-tikili-abseron-rayonu-masazir-azadliq-pr-60
#subscribe
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-abs-eron-rayon-masazir-qesebesi-153
https://arenda.az/satilir-2-otaqli-heyet-evi-villa-sabuncu-rayonu-koroglu-metrosu-mastaga-qes-sabuncu-rayonu-mastaga-qesebesi-5
https://arenda.az/satilir-5-otaqli-heyet-evi-villa-nizami-rayonu-xetai-metrosu-kesle-qes-nizami-rayonu-kesle-qesebesi-qasim-bey-zakir-kucesi-4-1
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2820
https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-1691
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2865
https://arenda.az/satilir-2-otaqli-yeni-tikili-xirdalan-kristal-abseron1-17
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2840
https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-1662
https://arenda.az/satilir-3-otaqli-heyet-evi-villa-abseron-rayonu-masazir-masazir-qesebesi-725
https://arenda.az/satilir-3-otaqli-heyet-evi-villa-quba-merkez
https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-qesebesi-1015
https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-abseron-rayon-masazir-qesebesi-qurtulus-93-yasayis-kompleksi-408
https://arenda.az/satilir-4-otaqli-heyet-evi-villa-abseron-rayonu-masazir-masazir-qesebesi-558
https://arenda.az/satilir-2-otaqli-kohne-tikili-qaradag-rayonu-lokbatan-qes-lokbatan-qesebesi-d-bunyadzade-kucesi
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-abseron-rayonu-masazir-qesebesi-qurtuluw-93-kompleksi
https://arenda.az/satilir-3-otaqli-yeni-tikili-nizami-rayonu-neftciler-metrosu-memmedili-serifli-kuc
https://arenda.az/satilir-3-otaqli-kohne-tikili-xetai-rayonu-hezi-aslanov-metrosu-ehmedli-xetai-ra-nu-gence-prospekti
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-qurtulus-93-361
https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-qesebesi-e-vahid-kucesi-109
https://arenda.az/satilir-3-otaqli-kohne-tikili-nerimanov-rayonu-neriman-nerimanov-metrosu-montin-qes-aga-nemetulla-kucesi-1
https://arenda.az/filtirli-axtaris/2/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max=
https://arenda.az/filtirli-axtaris/3/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max=
https://arenda.az/filtirli-axtaris/4/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max=
https://arenda.az/filtirli-axtaris/283/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max=
https://arenda.az/filtirli-axtaris/2/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max=
https://arenda.az/kohne-tikili-binalarin-satisi/
https://arenda.az/ehmedlide-kohne-tikili-evler/
https://arenda.az/hezi-aslanov-kohne-bina-evleri/
https://arenda.az/novxanida-villalar/
https://arenda.az/villa-satilir/
https://arenda.az/villa-evler/
https://arenda.az/qubada-villalar/
https://arenda.az/zabratda-heyet-evleri-2019/
https://arenda.az/badamdarda-kohne-tikili-evler/
https://arenda.az/9-cu-mikrorayon-kohne-tikili/
https://arenda.az/ehmedlide-evlerin-satisi/
https://arenda.az/genclikde-satilan-villalar/
https://arenda.az/hezi-aslanovda-heyet-evleri-satilir/
https://arenda.az/elmler-akademiyasi-ev-alqi-satqisi/
https://arenda.az/dernegulde-satilan-evler/
https://arenda.az/ilkin-odenissiz-ipoteka-evler/
https://arenda.az/bakixanov-qesebesinde-satilan-evler/
https://arenda.az/aaaf-park-kredit-2019/
https://arenda.az/nizami-metrosunda-evler/
https://arenda.az/nizami-metrosu-yaxinliginda-ev-alqi-satqisi/
https://arenda.az/xetai-metrosunda-satilan-evler/
https://arenda.az/binede-ucuz-heyet-evleri/
https://arenda.az/neftcilerde-satilan-3-otaqli-evler/
https://arenda.az/qarayevde-heyet-evleri/
https://arenda.az/kreditle-evlerin-satisi-1/
https://arenda.az/lokbatanda-bina-evleri/
https://arenda.az/qaracuxurda-bina_evleri/
https://arenda.az/elmlerde-satilan-evler/
https://arenda.az/en-bahali-villalar-1/
https://arenda.az/ehmedlide-kreditle-evler/
https://arenda.az/kiraye-evler-1/
https://arenda.az/ev-alqi-satqisi/
https://arenda.az/kiraye-ofisler/
https://arenda.az/dasinmaz-emlak/
https://arenda.az/kiraye-gunluk-2-otaqli-kohne-tikili-nesimi-rayonu-28-may-metrosu-azerbaycan-pr-44
https://arenda.az/kiraye-gunluk-2-otaqli-kohne-tikili-nesimi-rayonu-28-may-metrosu-28-may-metrosu-11
https://arenda.az/kiraye-gunluk-3-otaqli-kohne-tikili-sebail-rayonu-28-may-metrosu-denizkenari-milli-parkin-kenari
https://arenda.az/kiraye-gunluk-4-otaqli-heyet-evi-villa-gence-gence-molunn-arxasi-hesenli-qardasli-23
https://arenda.az/satilir-5-otaqli-heyet-evi-villa-xezer-rayonu-merdekan-28-may-2
https://arenda.az/kiraye-gunluk-2-otaqli-kohne-tikili-sebail-rayonu-sahil-metrosu-vidadi-133
https://arenda.az/kiraye-gunluk-2-otaqli-yeni-tikili-yasamal-rayonu-20-yanvar-metrosu-yeni-yasamal-qes-melisa-yasayis-kompleksi
https://arenda.az/kiraye-gunluk-2-otaqli-yeni-tikili-yasamal-rayonu-20-yanvar-metrosunun-yani
https://arenda.az/satilir-3-otaqli-heyet-evi-villa-abseron-rayonu-masazir-eliaga-vahid-kuc-yoncaliq-massivi-1
https://arenda.az/kiraye-ayliq-obyekt-bineqedi-rayonu-dernegul-metrosu-bineqedi-rayonu-ehmed-recebli-276-unvaninda-dernegul-bazari-ve-elit-tmm-yaxinligi
https://arenda.az/kiraye-ayliq-3-otaqli-yeni-tikili-abseron-rayonu-asagi-guzdek-cennet-park-yasayis-kompleksi-2
https://arenda.az/satilir-10-otaqli-heyet-evi-villa-nerimanov-rayonu-genclik-metrosu-boyuksor-qes-genclikde-milyonerler-mehellesi
https://arenda.az/satilir-5-otaqli-heyet-evi-villa-quba-qubanin-merkezinde-h-eliyev-prospekti
https://arenda.az/kiraye-ayliq-6-otaqli-heyet-evi-villa-xezer-rayonu-suvelan-suvelan-gres-qesebesinde
/agent/real-emlak-tebriz-dasinmaz-emlak-agentliyi/?type=1
/agent/real-emlak-tebriz-dasinmaz-emlak-agentliyi/?type=1
/agent/alo-estate-mmc-dasinmaz-emlak-agentliyi/?type=1
/agent/alo-estate-mmc-dasinmaz-emlak-agentliyi/?type=1
/agent/dostluq-dasinmaz-emlak-agentliyi/?type=1
/agent/dostluq-dasinmaz-emlak-agentliyi/?type=1
/filtirli-axtaris/?home_search=1&home_s=1&axtar=&site=1&user_num=27932
/filtirli-axtaris/?home_search=1&home_s=1&axtar=&site=1&user_num=27932
/agent/real-emlak-nerimanov-dasinmaz-emlak-agentliyi-1/?type=1
/agent/real-emlak-nerimanov-dasinmaz-emlak-agentliyi-1/?type=1
/istifadecilerin-reytinqi
https://arenda.az/

http://arenda.az/emlak
https://arenda.az/istifadeci-sertleri
https://arenda.az/faq

https://arenda.az/elan-yerlesdirme-qaydalari
https://arenda.az/elan-yerlesdir
https://arenda.az/xidmetler

https://arenda.az/haqqimizda
https://arenda.az/elaqe
#reklam
#
#
#
https://arenda.az/filtirli-axtaris/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max=&version=mobile
//www.liveinternet.ru/click
https://yigim.az/
tel:+99470 596 24 24
tel:+994 70 596 24 24
mailto:info@arenda.az
#
/arenda-az-saytinda-sexsi-kabinete-nece-daxi-ola-bilerem
#
https://arenda.az/login.php?login_type=2&ref=/filtirli-axtaris/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max=
https://arenda.az/login.php?login_type=3&ref=/filtirli-axtaris/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max=
#
#
https://arenda.az/login.php?login_type=2&ref=/filtirli-axtaris/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max=
https://arenda.az/login.php?login_type=3&ref=/filtirli-axtaris/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max=
#
#

In [6]:
# Filter links starting with "satilir"
satilir_links = [link for link in links if link.startswith('satilir') or '/satilir' in link]

print(f"Links with 'satilir': {len(satilir_links)}")
for link in satilir_links:
    # Make absolute URL if needed
    if link.startswith('/'):
        full_link = 'https://arenda.az' + link
    elif not link.startswith('http'):
        full_link = 'https://arenda.az/' + link
    else:
        full_link = link
    print(full_link)

Links with 'satilir': 30
https://arenda.az/satilir-3-otaqli-yeni-tikili-bineqedi-rayonu-nesimi-metrosu-9-cu-mikrorayon-mir-celal-137a-4
https://arenda.az/satilir-5-otaqli-yeni-tikili-xetai-rayonu-xetai-metrosu-baki-seheri-xetai-rayonu
https://arenda.az/satilir-4-otaqli-heyet-evi-villa-abseron-rayonu-masazir-eliaga-vahid-kuc-595
https://arenda.az/satilir-3-otaqli-yeni-tikili-nerimanov-rayonu-neriman-nerimanov-metrosu-montin-qes-nerimanov-rayonu-mayakovski-kucesi
https://arenda.az/satilir-1-otaqli-yeni-tikili-abseron-rayonu-masazir-azadliq-pr-60
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-abs-eron-rayon-masazir-qesebesi-153
https://arenda.az/satilir-2-otaqli-heyet-evi-villa-sabuncu-rayonu-koroglu-metrosu-mastaga-qes-sabuncu-rayonu-mastaga-qesebesi-5
https://arenda.az/satilir-5-otaqli-heyet-evi-villa-nizami-rayonu-xetai-metrosu-kesle-qes-nizami-rayonu-kesle-qesebesi-qasim-bey-zakir-kucesi-4-1
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2820
https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-1691
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2865
https://arenda.az/satilir-2-otaqli-yeni-tikili-xirdalan-kristal-abseron1-17
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2840
https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-1662
https://arenda.az/satilir-3-otaqli-heyet-evi-villa-abseron-rayonu-masazir-masazir-qesebesi-725
https://arenda.az/satilir-3-otaqli-heyet-evi-villa-quba-merkez
https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-qesebesi-1015
https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-abseron-rayon-masazir-qesebesi-qurtulus-93-yasayis-kompleksi-408
https://arenda.az/satilir-4-otaqli-heyet-evi-villa-abseron-rayonu-masazir-masazir-qesebesi-558
https://arenda.az/satilir-2-otaqli-kohne-tikili-qaradag-rayonu-lokbatan-qes-lokbatan-qesebesi-d-bunyadzade-kucesi
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-abseron-rayonu-masazir-qesebesi-qurtuluw-93-kompleksi
https://arenda.az/satilir-3-otaqli-yeni-tikili-nizami-rayonu-neftciler-metrosu-memmedili-serifli-kuc
https://arenda.az/satilir-3-otaqli-kohne-tikili-xetai-rayonu-hezi-aslanov-metrosu-ehmedli-xetai-ra-nu-gence-prospekti
https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-qurtulus-93-361
https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-qesebesi-e-vahid-kucesi-109
https://arenda.az/satilir-3-otaqli-kohne-tikili-nerimanov-rayonu-neriman-nerimanov-metrosu-montin-qes-aga-nemetulla-kucesi-1
https://arenda.az/satilir-5-otaqli-heyet-evi-villa-xezer-rayonu-merdekan-28-may-2
https://arenda.az/satilir-3-otaqli-heyet-evi-villa-abseron-rayonu-masazir-eliaga-vahid-kuc-yoncaliq-massivi-1
https://arenda.az/satilir-10-otaqli-heyet-evi-villa-nerimanov-rayonu-genclik-metrosu-boyuksor-qes-genclikde-milyonerler-mehellesi
https://arenda.az/satilir-5-otaqli-heyet-evi-villa-quba-qubanin-merkezinde-h-eliyev-prospekti

In [7]:
# Loop through all pages (1 to 296) and collect satilir links
all_satilir_links = []

base_url = 'https://arenda.az/filtirli-axtaris/{}/?home_search=1&lang=1&site=1&home_s=1&elan_novu%5B1%5D=1&emlak_novu%5B370%5D=370&emlak_novu%5B371%5D=371&emlak_novu%5B5%5D=5&emlak_novu%5B861%5D=861&price_min=&price_max=&axtar=&sahe_min=&sahe_max=&mertebe_min=&mertebe_max=&y_mertebe_min=&y_mertebe_max='

for page_num in tqdm(range(1, 297)):  # Pages 1 to 296
    try:
        # Navigate to page
        page_url = base_url.format(page_num)
        driver.get(page_url)
        time.sleep(2)  # Wait for page to load
        
        # Parse with BeautifulSoup
        page_source = driver.page_source
        bs = BeautifulSoup(page_source, 'html.parser')
        
        # Extract all links
        page_links = []
        for a_tag in bs.find_all('a', href=True):
            href = a_tag['href']
            page_links.append(href)
        
        # Filter satilir links
        satilir_links_page = [link for link in page_links if 'satilir' in link]
        
        # Convert to absolute URLs
        for link in satilir_links_page:
            if link.startswith('/'):
                full_link = 'https://arenda.az' + link
            elif not link.startswith('http'):
                full_link = 'https://arenda.az/' + link
            else:
                full_link = link
            
            # Avoid duplicates
            if full_link not in all_satilir_links:
                all_satilir_links.append(full_link)
        
        print(f"Page {page_num}: Found {len(satilir_links_page)} satilir links (Total: {len(all_satilir_links)})")
        
    except Exception as e:
        print(f"Error on page {page_num}: {e}")
        continue

print(f"\n✓ Scraping complete!")
print(f"Total unique satilir links collected: {len(all_satilir_links)}")

  0%|          | 0/296 [00:00<?, ?it/s]

  0%|          | 1/296 [00:04<23:00,  4.68s/it]

Page 1: Found 32 satilir links (Total: 32)

  1%|          | 2/296 [00:08<21:34,  4.40s/it]

Page 2: Found 31 satilir links (Total: 54)

  1%|          | 3/296 [00:13<20:59,  4.30s/it]

Page 3: Found 34 satilir links (Total: 78)

  1%|▏         | 4/296 [00:17<21:19,  4.38s/it]

Page 4: Found 31 satilir links (Total: 99)

  2%|▏         | 5/296 [00:21<20:59,  4.33s/it]

Page 5: Found 31 satilir links (Total: 121)

  2%|▏         | 6/296 [00:26<20:50,  4.31s/it]

Page 6: Found 31 satilir links (Total: 143)

  2%|▏         | 7/296 [00:30<20:53,  4.34s/it]

Page 7: Found 32 satilir links (Total: 166)

  3%|▎         | 8/296 [00:34<21:05,  4.39s/it]

Page 8: Found 32 satilir links (Total: 187)

  3%|▎         | 9/296 [00:39<20:58,  4.39s/it]

Page 9: Found 31 satilir links (Total: 208)

  3%|▎         | 10/296 [00:43<20:46,  4.36s/it]

Page 10: Found 30 satilir links (Total: 229)

  4%|▎         | 11/296 [00:48<20:50,  4.39s/it]

Page 11: Found 33 satilir links (Total: 252)

  4%|▍         | 12/296 [00:52<20:28,  4.32s/it]

Page 12: Found 31 satilir links (Total: 274)

  4%|▍         | 13/296 [00:57<22:12,  4.71s/it]

Page 13: Found 34 satilir links (Total: 297)

  5%|▍         | 14/296 [01:02<21:45,  4.63s/it]

Page 14: Found 31 satilir links (Total: 319)

  5%|▌         | 15/296 [01:06<20:56,  4.47s/it]

Page 15: Found 31 satilir links (Total: 341)

  5%|▌         | 16/296 [01:10<20:17,  4.35s/it]

Page 16: Found 32 satilir links (Total: 363)

  6%|▌         | 17/296 [01:14<20:06,  4.32s/it]

Page 17: Found 32 satilir links (Total: 386)

  6%|▌         | 18/296 [01:19<20:20,  4.39s/it]

Page 18: Found 32 satilir links (Total: 407)

  6%|▋         | 19/296 [01:23<20:16,  4.39s/it]

Page 19: Found 33 satilir links (Total: 430)

  7%|▋         | 20/296 [01:27<19:57,  4.34s/it]

Page 20: Found 31 satilir links (Total: 451)

  7%|▋         | 21/296 [01:32<19:41,  4.30s/it]

Page 21: Found 31 satilir links (Total: 472)

  7%|▋         | 22/296 [01:36<19:30,  4.27s/it]

Page 22: Found 33 satilir links (Total: 493)

  8%|▊         | 23/296 [01:40<19:20,  4.25s/it]

Page 23: Found 33 satilir links (Total: 515)

  8%|▊         | 24/296 [01:45<19:35,  4.32s/it]

Page 24: Found 30 satilir links (Total: 536)

  8%|▊         | 25/296 [01:49<19:18,  4.28s/it]

Page 25: Found 30 satilir links (Total: 557)

  9%|▉         | 26/296 [01:53<19:19,  4.29s/it]

Page 26: Found 31 satilir links (Total: 578)

  9%|▉         | 27/296 [01:58<19:34,  4.37s/it]

Page 27: Found 31 satilir links (Total: 600)

  9%|▉         | 28/296 [02:02<19:53,  4.46s/it]

Page 28: Found 32 satilir links (Total: 622)

 10%|▉         | 29/296 [02:07<19:45,  4.44s/it]

Page 29: Found 31 satilir links (Total: 644)

 10%|█         | 30/296 [02:11<19:40,  4.44s/it]

Page 30: Found 33 satilir links (Total: 666)

 10%|█         | 31/296 [02:16<19:38,  4.45s/it]

Page 31: Found 34 satilir links (Total: 688)

 11%|█         | 32/296 [02:20<19:32,  4.44s/it]

Page 32: Found 32 satilir links (Total: 710)

 11%|█         | 33/296 [02:24<19:11,  4.38s/it]

Page 33: Found 31 satilir links (Total: 731)

 11%|█▏        | 34/296 [02:29<19:14,  4.41s/it]

Page 34: Found 32 satilir links (Total: 752)

 12%|█▏        | 35/296 [02:33<18:35,  4.28s/it]

Page 35: Found 33 satilir links (Total: 775)

 12%|█▏        | 36/296 [02:37<18:42,  4.32s/it]

Page 36: Found 31 satilir links (Total: 796)

 12%|█▎        | 37/296 [02:41<18:34,  4.30s/it]

Page 37: Found 30 satilir links (Total: 817)

 13%|█▎        | 38/296 [02:46<18:31,  4.31s/it]

Page 38: Found 32 satilir links (Total: 840)

 13%|█▎        | 39/296 [02:50<18:01,  4.21s/it]

Page 39: Found 33 satilir links (Total: 861)

 14%|█▎        | 40/296 [02:54<17:49,  4.18s/it]

Page 40: Found 32 satilir links (Total: 882)

 14%|█▍        | 41/296 [02:59<18:44,  4.41s/it]

Page 41: Found 30 satilir links (Total: 903)

 14%|█▍        | 42/296 [03:04<19:20,  4.57s/it]

Page 42: Found 32 satilir links (Total: 926)

 15%|█▍        | 43/296 [03:08<19:19,  4.58s/it]

Page 43: Found 32 satilir links (Total: 948)

 15%|█▍        | 44/296 [03:13<19:19,  4.60s/it]

Page 44: Found 35 satilir links (Total: 971)

 15%|█▌        | 45/296 [03:18<19:43,  4.72s/it]

Page 45: Found 33 satilir links (Total: 993)

 16%|█▌        | 46/296 [03:22<19:27,  4.67s/it]

Page 46: Found 35 satilir links (Total: 1016)

 16%|█▌        | 47/296 [03:28<20:52,  5.03s/it]

Page 47: Found 31 satilir links (Total: 1038)

 16%|█▌        | 48/296 [03:33<20:37,  4.99s/it]

Page 48: Found 30 satilir links (Total: 1059)

 17%|█▋        | 49/296 [03:38<20:24,  4.96s/it]

Page 49: Found 34 satilir links (Total: 1081)

 17%|█▋        | 50/296 [03:43<20:10,  4.92s/it]

Page 50: Found 31 satilir links (Total: 1102)

 17%|█▋        | 51/296 [03:48<19:54,  4.88s/it]

Page 51: Found 32 satilir links (Total: 1123)

 18%|█▊        | 52/296 [03:52<19:43,  4.85s/it]

Page 52: Found 31 satilir links (Total: 1144)

 18%|█▊        | 53/296 [03:57<19:38,  4.85s/it]

Page 53: Found 32 satilir links (Total: 1167)

 18%|█▊        | 54/296 [04:02<19:22,  4.80s/it]

Page 54: Found 35 satilir links (Total: 1191)

 19%|█▊        | 55/296 [04:08<20:50,  5.19s/it]

Page 55: Found 33 satilir links (Total: 1212)

 19%|█▉        | 56/296 [04:13<20:27,  5.12s/it]

Page 56: Found 32 satilir links (Total: 1234)

 19%|█▉        | 57/296 [04:18<19:43,  4.95s/it]

Page 57: Found 31 satilir links (Total: 1255)

 20%|█▉        | 58/296 [04:22<19:31,  4.92s/it]

Page 58: Found 34 satilir links (Total: 1276)

 20%|█▉        | 59/296 [04:27<19:03,  4.82s/it]

Page 59: Found 33 satilir links (Total: 1297)

 20%|██        | 60/296 [04:32<19:09,  4.87s/it]

Page 60: Found 33 satilir links (Total: 1319)

 21%|██        | 61/296 [04:37<19:27,  4.97s/it]

Page 61: Found 33 satilir links (Total: 1341)

 21%|██        | 62/296 [04:42<19:03,  4.89s/it]

Page 62: Found 31 satilir links (Total: 1362)

 21%|██▏       | 63/296 [04:47<18:53,  4.87s/it]

Page 63: Found 31 satilir links (Total: 1384)

 22%|██▏       | 64/296 [04:51<18:27,  4.78s/it]

Page 64: Found 32 satilir links (Total: 1405)

 22%|██▏       | 65/296 [04:56<18:06,  4.70s/it]

Page 65: Found 32 satilir links (Total: 1426)

 22%|██▏       | 66/296 [05:01<18:01,  4.70s/it]

Page 66: Found 33 satilir links (Total: 1447)

 23%|██▎       | 67/296 [05:05<17:28,  4.58s/it]

Page 67: Found 32 satilir links (Total: 1469)

 23%|██▎       | 68/296 [05:09<17:27,  4.59s/it]

Page 68: Found 31 satilir links (Total: 1490)

 23%|██▎       | 69/296 [05:14<16:59,  4.49s/it]

Page 69: Found 34 satilir links (Total: 1511)

 24%|██▎       | 70/296 [05:18<16:38,  4.42s/it]

Page 70: Found 32 satilir links (Total: 1532)

 24%|██▍       | 71/296 [05:22<16:39,  4.44s/it]

Page 71: Found 34 satilir links (Total: 1554)

 24%|██▍       | 72/296 [05:27<16:22,  4.38s/it]

Page 72: Found 30 satilir links (Total: 1575)

 25%|██▍       | 73/296 [05:31<16:18,  4.39s/it]

Page 73: Found 34 satilir links (Total: 1596)

 25%|██▌       | 74/296 [05:35<16:10,  4.37s/it]

Page 74: Found 33 satilir links (Total: 1617)

 25%|██▌       | 75/296 [05:40<16:02,  4.36s/it]

Page 75: Found 32 satilir links (Total: 1639)

 26%|██▌       | 76/296 [05:44<15:44,  4.29s/it]

Page 76: Found 31 satilir links (Total: 1660)

 26%|██▌       | 77/296 [05:48<15:56,  4.37s/it]

Page 77: Found 34 satilir links (Total: 1682)

 26%|██▋       | 78/296 [05:53<16:17,  4.48s/it]

Page 78: Found 33 satilir links (Total: 1703)

 27%|██▋       | 79/296 [05:58<16:02,  4.44s/it]

Page 79: Found 31 satilir links (Total: 1724)

 27%|██▋       | 80/296 [06:02<16:12,  4.50s/it]

Page 80: Found 32 satilir links (Total: 1746)

 27%|██▋       | 81/296 [06:07<16:56,  4.73s/it]

Page 81: Found 31 satilir links (Total: 1767)

 28%|██▊       | 82/296 [06:12<16:21,  4.59s/it]

Page 82: Found 31 satilir links (Total: 1788)

 28%|██▊       | 83/296 [06:16<16:07,  4.54s/it]

Page 83: Found 34 satilir links (Total: 1809)

 28%|██▊       | 84/296 [06:21<16:12,  4.59s/it]

Page 84: Found 33 satilir links (Total: 1831)

 29%|██▊       | 85/296 [06:25<16:05,  4.57s/it]

Page 85: Found 35 satilir links (Total: 1852)

 29%|██▉       | 86/296 [06:31<16:49,  4.81s/it]

Page 86: Found 32 satilir links (Total: 1873)

 29%|██▉       | 87/296 [06:35<16:34,  4.76s/it]

Page 87: Found 32 satilir links (Total: 1894)

 30%|██▉       | 88/296 [06:41<17:13,  4.97s/it]

Page 88: Found 35 satilir links (Total: 1915)

 30%|███       | 89/296 [06:46<17:00,  4.93s/it]

Page 89: Found 31 satilir links (Total: 1936)

 30%|███       | 90/296 [06:50<16:37,  4.84s/it]

Page 90: Found 31 satilir links (Total: 1957)

 31%|███       | 91/296 [06:55<16:34,  4.85s/it]

Page 91: Found 31 satilir links (Total: 1978)

 31%|███       | 92/296 [07:00<16:33,  4.87s/it]

Page 92: Found 34 satilir links (Total: 2000)

 31%|███▏      | 93/296 [07:06<17:35,  5.20s/it]

Page 93: Found 32 satilir links (Total: 2021)

 32%|███▏      | 94/296 [07:11<17:35,  5.23s/it]

Page 94: Found 33 satilir links (Total: 2042)

 32%|███▏      | 95/296 [07:16<17:15,  5.15s/it]

Page 95: Found 30 satilir links (Total: 2063)

 32%|███▏      | 96/296 [07:21<16:49,  5.05s/it]

Page 96: Found 36 satilir links (Total: 2084)

 33%|███▎      | 97/296 [07:26<16:24,  4.95s/it]

Page 97: Found 33 satilir links (Total: 2105)

 33%|███▎      | 98/296 [07:31<16:05,  4.88s/it]

Page 98: Found 33 satilir links (Total: 2127)

 33%|███▎      | 99/296 [07:35<15:30,  4.73s/it]

Page 99: Found 32 satilir links (Total: 2148)

 34%|███▍      | 100/296 [07:43<18:15,  5.59s/it]

Page 100: Found 34 satilir links (Total: 2169)

 34%|███▍      | 101/296 [07:47<16:56,  5.21s/it]

Page 101: Found 31 satilir links (Total: 2190)

 34%|███▍      | 102/296 [07:51<16:13,  5.02s/it]

Page 102: Found 31 satilir links (Total: 2211)

 35%|███▍      | 103/296 [07:56<15:23,  4.78s/it]

Page 103: Found 32 satilir links (Total: 2232)

 35%|███▌      | 104/296 [08:00<14:47,  4.62s/it]

Page 104: Found 33 satilir links (Total: 2253)

 35%|███▌      | 105/296 [08:04<14:31,  4.56s/it]

Page 105: Found 31 satilir links (Total: 2274)

 36%|███▌      | 106/296 [08:09<14:08,  4.46s/it]

Page 106: Found 33 satilir links (Total: 2295)

 36%|███▌      | 107/296 [08:13<13:52,  4.41s/it]

Page 107: Found 31 satilir links (Total: 2316)

 36%|███▋      | 108/296 [08:17<13:45,  4.39s/it]

Page 108: Found 34 satilir links (Total: 2338)

 37%|███▋      | 109/296 [08:22<13:43,  4.40s/it]

Page 109: Found 32 satilir links (Total: 2359)

 37%|███▋      | 110/296 [08:26<13:51,  4.47s/it]

Page 110: Found 33 satilir links (Total: 2381)

 38%|███▊      | 111/296 [08:31<13:39,  4.43s/it]

Page 111: Found 31 satilir links (Total: 2402)

 38%|███▊      | 112/296 [08:35<13:55,  4.54s/it]

Page 112: Found 31 satilir links (Total: 2423)

 38%|███▊      | 113/296 [08:40<14:16,  4.68s/it]

Page 113: Found 33 satilir links (Total: 2444)

 39%|███▊      | 114/296 [08:45<13:55,  4.59s/it]

Page 114: Found 35 satilir links (Total: 2465)

 39%|███▉      | 115/296 [08:49<13:39,  4.53s/it]

Page 115: Found 32 satilir links (Total: 2486)

 39%|███▉      | 116/296 [08:53<13:16,  4.42s/it]

Page 116: Found 31 satilir links (Total: 2507)

 40%|███▉      | 117/296 [08:57<12:50,  4.30s/it]

Page 117: Found 32 satilir links (Total: 2528)

 40%|███▉      | 118/296 [09:03<13:38,  4.60s/it]

Page 118: Found 33 satilir links (Total: 2549)

 40%|████      | 119/296 [09:07<13:22,  4.53s/it]

Page 119: Found 32 satilir links (Total: 2570)

 41%|████      | 120/296 [09:11<13:02,  4.45s/it]

Page 120: Found 31 satilir links (Total: 2591)

 41%|████      | 121/296 [09:15<12:38,  4.33s/it]

Page 121: Found 32 satilir links (Total: 2613)

 41%|████      | 122/296 [09:20<12:38,  4.36s/it]

Page 122: Found 31 satilir links (Total: 2634)

 42%|████▏     | 123/296 [09:24<12:28,  4.33s/it]

Page 123: Found 31 satilir links (Total: 2655)

 42%|████▏     | 124/296 [09:28<12:18,  4.29s/it]

Page 124: Found 34 satilir links (Total: 2676)

 42%|████▏     | 125/296 [09:33<12:35,  4.42s/it]

Page 125: Found 31 satilir links (Total: 2697)

 43%|████▎     | 126/296 [09:37<12:18,  4.34s/it]

Page 126: Found 32 satilir links (Total: 2718)

 43%|████▎     | 127/296 [09:41<12:12,  4.33s/it]

Page 127: Found 32 satilir links (Total: 2739)

 43%|████▎     | 128/296 [09:46<12:10,  4.35s/it]

Page 128: Found 31 satilir links (Total: 2760)

 44%|████▎     | 129/296 [09:50<11:55,  4.29s/it]

Page 129: Found 31 satilir links (Total: 2781)

 44%|████▍     | 130/296 [09:54<11:52,  4.29s/it]

Page 130: Found 30 satilir links (Total: 2802)

 44%|████▍     | 131/296 [09:58<11:39,  4.24s/it]

Page 131: Found 31 satilir links (Total: 2823)

 45%|████▍     | 132/296 [10:03<11:39,  4.26s/it]

Page 132: Found 31 satilir links (Total: 2844)

 45%|████▍     | 133/296 [10:07<11:33,  4.25s/it]

Page 133: Found 31 satilir links (Total: 2865)

 45%|████▌     | 134/296 [10:11<11:24,  4.23s/it]

Page 134: Found 34 satilir links (Total: 2886)

 46%|████▌     | 135/296 [10:15<11:26,  4.26s/it]

Page 135: Found 30 satilir links (Total: 2907)

 46%|████▌     | 136/296 [10:20<11:21,  4.26s/it]

Page 136: Found 34 satilir links (Total: 2928)

 46%|████▋     | 137/296 [10:24<11:14,  4.24s/it]

Page 137: Found 34 satilir links (Total: 2949)

 47%|████▋     | 138/296 [10:28<11:17,  4.29s/it]

Page 138: Found 32 satilir links (Total: 2970)

 47%|████▋     | 139/296 [10:33<11:14,  4.30s/it]

Page 139: Found 33 satilir links (Total: 2991)

 47%|████▋     | 140/296 [10:37<11:01,  4.24s/it]

Page 140: Found 32 satilir links (Total: 3012)

 48%|████▊     | 141/296 [10:41<10:57,  4.24s/it]

Page 141: Found 31 satilir links (Total: 3033)

 48%|████▊     | 142/296 [10:45<10:54,  4.25s/it]

Page 142: Found 34 satilir links (Total: 3054)

 48%|████▊     | 143/296 [10:49<10:49,  4.25s/it]

Page 143: Found 30 satilir links (Total: 3075)

 49%|████▊     | 144/296 [10:54<10:42,  4.23s/it]

Page 144: Found 32 satilir links (Total: 3096)

 49%|████▉     | 145/296 [10:58<10:39,  4.23s/it]

Page 145: Found 33 satilir links (Total: 3117)

 49%|████▉     | 146/296 [11:02<10:28,  4.19s/it]

Page 146: Found 34 satilir links (Total: 3138)

 50%|████▉     | 147/296 [11:06<10:22,  4.18s/it]

Page 147: Found 33 satilir links (Total: 3159)

 50%|█████     | 148/296 [11:10<10:24,  4.22s/it]

Page 148: Found 33 satilir links (Total: 3180)

 50%|█████     | 149/296 [11:15<10:13,  4.17s/it]

Page 149: Found 32 satilir links (Total: 3201)

 51%|█████     | 150/296 [11:19<10:20,  4.25s/it]

Page 150: Found 30 satilir links (Total: 3222)

 51%|█████     | 151/296 [11:23<10:16,  4.25s/it]

Page 151: Found 30 satilir links (Total: 3243)

 51%|█████▏    | 152/296 [11:28<10:18,  4.30s/it]

Page 152: Found 32 satilir links (Total: 3264)

 52%|█████▏    | 153/296 [11:32<10:20,  4.34s/it]

Page 153: Found 34 satilir links (Total: 3285)

 52%|█████▏    | 154/296 [11:36<10:16,  4.34s/it]

Page 154: Found 34 satilir links (Total: 3306)

 52%|█████▏    | 155/296 [11:41<10:23,  4.42s/it]

Page 155: Found 33 satilir links (Total: 3327)

 53%|█████▎    | 156/296 [11:45<10:06,  4.34s/it]

Page 156: Found 30 satilir links (Total: 3348)

 53%|█████▎    | 157/296 [11:50<10:04,  4.35s/it]

Page 157: Found 34 satilir links (Total: 3369)

 53%|█████▎    | 158/296 [11:54<09:52,  4.30s/it]

Page 158: Found 35 satilir links (Total: 3390)

 54%|█████▎    | 159/296 [11:58<09:43,  4.26s/it]

Page 159: Found 31 satilir links (Total: 3411)

 54%|█████▍    | 160/296 [12:02<09:36,  4.24s/it]

Page 160: Found 32 satilir links (Total: 3432)

 54%|█████▍    | 161/296 [12:06<09:32,  4.24s/it]

Page 161: Found 30 satilir links (Total: 3453)

 55%|█████▍    | 162/296 [12:10<09:27,  4.23s/it]

Page 162: Found 33 satilir links (Total: 3474)

 55%|█████▌    | 163/296 [12:15<09:24,  4.25s/it]

Page 163: Found 31 satilir links (Total: 3495)

 55%|█████▌    | 164/296 [12:19<09:22,  4.26s/it]

Page 164: Found 33 satilir links (Total: 3516)

 56%|█████▌    | 165/296 [12:23<09:20,  4.28s/it]

Page 165: Found 34 satilir links (Total: 3537)

 56%|█████▌    | 166/296 [12:27<09:06,  4.21s/it]

Page 166: Found 33 satilir links (Total: 3558)

 56%|█████▋    | 167/296 [12:32<09:02,  4.20s/it]

Page 167: Found 31 satilir links (Total: 3579)

 57%|█████▋    | 168/296 [12:36<09:06,  4.27s/it]

Page 168: Found 30 satilir links (Total: 3600)

 57%|█████▋    | 169/296 [12:40<09:02,  4.28s/it]

Page 169: Found 34 satilir links (Total: 3621)

 57%|█████▋    | 170/296 [12:45<09:05,  4.33s/it]

Page 170: Found 30 satilir links (Total: 3642)

 58%|█████▊    | 171/296 [12:49<09:02,  4.34s/it]

Page 171: Found 33 satilir links (Total: 3663)

 58%|█████▊    | 172/296 [12:54<09:00,  4.36s/it]

Page 172: Found 33 satilir links (Total: 3684)

 58%|█████▊    | 173/296 [12:58<08:51,  4.32s/it]

Page 173: Found 33 satilir links (Total: 3705)

 59%|█████▉    | 174/296 [13:02<08:46,  4.32s/it]

Page 174: Found 31 satilir links (Total: 3726)

 59%|█████▉    | 175/296 [13:06<08:37,  4.27s/it]

Page 175: Found 32 satilir links (Total: 3747)

 59%|█████▉    | 176/296 [13:11<08:39,  4.33s/it]

Page 176: Found 33 satilir links (Total: 3768)

 60%|█████▉    | 177/296 [13:15<08:29,  4.28s/it]

Page 177: Found 31 satilir links (Total: 3789)

 60%|██████    | 178/296 [13:19<08:19,  4.23s/it]

Page 178: Found 32 satilir links (Total: 3810)

 60%|██████    | 179/296 [13:23<08:19,  4.27s/it]

Page 179: Found 31 satilir links (Total: 3831)

 61%|██████    | 180/296 [13:27<08:07,  4.21s/it]

Page 180: Found 32 satilir links (Total: 3852)

 61%|██████    | 181/296 [13:31<07:58,  4.16s/it]

Page 181: Found 31 satilir links (Total: 3873)

 61%|██████▏   | 182/296 [13:36<07:56,  4.18s/it]

Page 182: Found 31 satilir links (Total: 3894)

 62%|██████▏   | 183/296 [13:40<07:51,  4.17s/it]

Page 183: Found 30 satilir links (Total: 3915)

 62%|██████▏   | 184/296 [13:44<07:50,  4.20s/it]

Page 184: Found 36 satilir links (Total: 3936)

 62%|██████▎   | 185/296 [13:48<07:47,  4.21s/it]

Page 185: Found 32 satilir links (Total: 3957)

 63%|██████▎   | 186/296 [13:52<07:39,  4.18s/it]

Page 186: Found 31 satilir links (Total: 3978)

 63%|██████▎   | 187/296 [13:57<07:34,  4.17s/it]

Page 187: Found 33 satilir links (Total: 3999)

 64%|██████▎   | 188/296 [14:01<07:30,  4.17s/it]

Page 188: Found 32 satilir links (Total: 4021)

 64%|██████▍   | 189/296 [14:05<07:31,  4.22s/it]

Page 189: Found 31 satilir links (Total: 4042)

 64%|██████▍   | 190/296 [14:09<07:22,  4.18s/it]

Page 190: Found 31 satilir links (Total: 4063)

 65%|██████▍   | 191/296 [14:13<07:16,  4.16s/it]

Page 191: Found 33 satilir links (Total: 4084)

 65%|██████▍   | 192/296 [14:18<07:15,  4.18s/it]

Page 192: Found 32 satilir links (Total: 4105)

 65%|██████▌   | 193/296 [14:22<07:05,  4.13s/it]

Page 193: Found 33 satilir links (Total: 4126)

 66%|██████▌   | 194/296 [14:26<06:56,  4.08s/it]

Page 194: Found 33 satilir links (Total: 4147)

 66%|██████▌   | 195/296 [14:30<06:56,  4.12s/it]

Page 195: Found 31 satilir links (Total: 4168)

 66%|██████▌   | 196/296 [14:34<06:58,  4.19s/it]

Page 196: Found 32 satilir links (Total: 4189)

 67%|██████▋   | 197/296 [14:38<06:54,  4.19s/it]

Page 197: Found 32 satilir links (Total: 4210)

 67%|██████▋   | 198/296 [14:42<06:50,  4.19s/it]

Page 198: Found 31 satilir links (Total: 4231)

 67%|██████▋   | 199/296 [14:47<06:46,  4.19s/it]

Page 199: Found 31 satilir links (Total: 4252)

 68%|██████▊   | 200/296 [14:51<06:44,  4.21s/it]

Page 200: Found 33 satilir links (Total: 4274)

 68%|██████▊   | 201/296 [14:55<06:40,  4.22s/it]

Page 201: Found 31 satilir links (Total: 4295)

 68%|██████▊   | 202/296 [15:00<06:40,  4.27s/it]

Page 202: Found 34 satilir links (Total: 4316)

 69%|██████▊   | 203/296 [15:04<06:34,  4.24s/it]

Page 203: Found 30 satilir links (Total: 4337)

 69%|██████▉   | 204/296 [15:08<06:27,  4.21s/it]

Page 204: Found 33 satilir links (Total: 4358)

 69%|██████▉   | 205/296 [15:12<06:30,  4.29s/it]

Page 205: Found 32 satilir links (Total: 4379)

 70%|██████▉   | 206/296 [15:16<06:21,  4.24s/it]

Page 206: Found 33 satilir links (Total: 4400)

 70%|██████▉   | 207/296 [15:21<06:18,  4.25s/it]

Page 207: Found 35 satilir links (Total: 4421)

 70%|███████   | 208/296 [15:25<06:12,  4.23s/it]

Page 208: Found 31 satilir links (Total: 4442)

 71%|███████   | 209/296 [15:29<06:06,  4.21s/it]

Page 209: Found 31 satilir links (Total: 4463)

 71%|███████   | 210/296 [15:33<06:03,  4.23s/it]

Page 210: Found 32 satilir links (Total: 4484)

 71%|███████▏  | 211/296 [15:38<06:03,  4.28s/it]

Page 211: Found 34 satilir links (Total: 4505)

 72%|███████▏  | 212/296 [15:42<05:58,  4.27s/it]

Page 212: Found 32 satilir links (Total: 4526)

 72%|███████▏  | 213/296 [15:46<05:54,  4.27s/it]

Page 213: Found 32 satilir links (Total: 4547)

 72%|███████▏  | 214/296 [15:50<05:43,  4.19s/it]

Page 214: Found 33 satilir links (Total: 4568)

 73%|███████▎  | 215/296 [15:54<05:39,  4.20s/it]

Page 215: Found 31 satilir links (Total: 4589)

 73%|███████▎  | 216/296 [15:59<05:32,  4.16s/it]

Page 216: Found 32 satilir links (Total: 4610)

 73%|███████▎  | 217/296 [16:03<05:29,  4.17s/it]

Page 217: Found 33 satilir links (Total: 4631)

 74%|███████▎  | 218/296 [16:08<05:39,  4.35s/it]

Page 218: Found 33 satilir links (Total: 4652)

 74%|███████▍  | 219/296 [16:12<05:32,  4.32s/it]

Page 219: Found 32 satilir links (Total: 4673)

 74%|███████▍  | 220/296 [16:16<05:33,  4.38s/it]

Page 220: Found 33 satilir links (Total: 4694)

 75%|███████▍  | 221/296 [16:21<05:28,  4.38s/it]

Page 221: Found 31 satilir links (Total: 4715)

 75%|███████▌  | 222/296 [16:25<05:21,  4.34s/it]

Page 222: Found 31 satilir links (Total: 4736)

 75%|███████▌  | 223/296 [16:29<05:15,  4.32s/it]

Page 223: Found 31 satilir links (Total: 4757)

 76%|███████▌  | 224/296 [16:33<05:08,  4.29s/it]

Page 224: Found 32 satilir links (Total: 4778)

 76%|███████▌  | 225/296 [16:37<04:59,  4.22s/it]

Page 225: Found 33 satilir links (Total: 4799)

 76%|███████▋  | 226/296 [16:42<05:08,  4.41s/it]

Page 226: Found 32 satilir links (Total: 4820)

 77%|███████▋  | 227/296 [16:46<04:59,  4.33s/it]

Page 227: Found 33 satilir links (Total: 4841)

 77%|███████▋  | 228/296 [16:51<04:54,  4.33s/it]

Page 228: Found 32 satilir links (Total: 4862)

 77%|███████▋  | 229/296 [16:55<04:52,  4.37s/it]

Page 229: Found 31 satilir links (Total: 4883)

 78%|███████▊  | 230/296 [17:00<04:46,  4.35s/it]

Page 230: Found 33 satilir links (Total: 4904)

 78%|███████▊  | 231/296 [17:07<05:38,  5.20s/it]

Page 231: Found 32 satilir links (Total: 4925)

 78%|███████▊  | 232/296 [17:11<05:16,  4.95s/it]

Page 232: Found 32 satilir links (Total: 4946)

 79%|███████▊  | 233/296 [17:15<04:58,  4.73s/it]

Page 233: Found 31 satilir links (Total: 4967)

 79%|███████▉  | 234/296 [17:19<04:41,  4.54s/it]

Page 234: Found 34 satilir links (Total: 4988)

 79%|███████▉  | 235/296 [17:24<04:30,  4.44s/it]

Page 235: Found 31 satilir links (Total: 5009)

 80%|███████▉  | 236/296 [17:28<04:22,  4.38s/it]

Page 236: Found 33 satilir links (Total: 5030)

 80%|████████  | 237/296 [17:32<04:16,  4.34s/it]

Page 237: Found 32 satilir links (Total: 5051)

 80%|████████  | 238/296 [17:36<04:10,  4.32s/it]

Page 238: Found 34 satilir links (Total: 5072)

 81%|████████  | 239/296 [17:41<04:05,  4.31s/it]

Page 239: Found 34 satilir links (Total: 5093)

 81%|████████  | 240/296 [17:45<03:59,  4.27s/it]

Page 240: Found 34 satilir links (Total: 5114)

 81%|████████▏ | 241/296 [17:49<03:54,  4.26s/it]

Page 241: Found 33 satilir links (Total: 5135)

 82%|████████▏ | 242/296 [17:53<03:50,  4.27s/it]

Page 242: Found 34 satilir links (Total: 5156)

 82%|████████▏ | 243/296 [17:58<03:44,  4.24s/it]

Page 243: Found 34 satilir links (Total: 5177)

 82%|████████▏ | 244/296 [18:02<03:39,  4.22s/it]

Page 244: Found 31 satilir links (Total: 5198)

 83%|████████▎ | 245/296 [18:06<03:34,  4.21s/it]

Page 245: Found 33 satilir links (Total: 5219)

 83%|████████▎ | 246/296 [18:10<03:32,  4.25s/it]

Page 246: Found 31 satilir links (Total: 5240)

 83%|████████▎ | 247/296 [18:14<03:26,  4.22s/it]

Page 247: Found 32 satilir links (Total: 5261)

 84%|████████▍ | 248/296 [18:19<03:21,  4.20s/it]

Page 248: Found 31 satilir links (Total: 5282)

 84%|████████▍ | 249/296 [18:23<03:18,  4.22s/it]

Page 249: Found 33 satilir links (Total: 5303)

 84%|████████▍ | 250/296 [18:27<03:13,  4.20s/it]

Page 250: Found 31 satilir links (Total: 5324)

 85%|████████▍ | 251/296 [18:31<03:08,  4.18s/it]

Page 251: Found 34 satilir links (Total: 5345)

 85%|████████▌ | 252/296 [18:36<03:06,  4.24s/it]

Page 252: Found 32 satilir links (Total: 5366)

 85%|████████▌ | 253/296 [18:40<03:03,  4.27s/it]

Page 253: Found 32 satilir links (Total: 5387)

 86%|████████▌ | 254/296 [18:44<02:58,  4.26s/it]

Page 254: Found 30 satilir links (Total: 5408)

 86%|████████▌ | 255/296 [18:49<02:59,  4.38s/it]

Page 255: Found 32 satilir links (Total: 5429)

 86%|████████▋ | 256/296 [18:54<03:10,  4.76s/it]

Page 256: Found 31 satilir links (Total: 5450)

 87%|████████▋ | 257/296 [18:59<02:59,  4.61s/it]

Page 257: Found 30 satilir links (Total: 5471)

 87%|████████▋ | 258/296 [19:03<02:55,  4.61s/it]

Page 258: Found 32 satilir links (Total: 5492)

 88%|████████▊ | 259/296 [19:08<02:48,  4.56s/it]

Page 259: Found 33 satilir links (Total: 5513)

 88%|████████▊ | 260/296 [19:12<02:41,  4.48s/it]

Page 260: Found 33 satilir links (Total: 5534)

 88%|████████▊ | 261/296 [19:17<02:37,  4.51s/it]

Page 261: Found 35 satilir links (Total: 5553)

 89%|████████▊ | 262/296 [19:21<02:31,  4.46s/it]

Page 262: Found 34 satilir links (Total: 5574)

 89%|████████▉ | 263/296 [19:25<02:28,  4.49s/it]

Page 263: Found 31 satilir links (Total: 5595)

 89%|████████▉ | 264/296 [19:30<02:19,  4.36s/it]

Page 264: Found 33 satilir links (Total: 5616)

 90%|████████▉ | 265/296 [19:34<02:13,  4.30s/it]

Page 265: Found 33 satilir links (Total: 5637)

 90%|████████▉ | 266/296 [19:38<02:07,  4.26s/it]

Page 266: Found 32 satilir links (Total: 5658)

 90%|█████████ | 267/296 [19:42<02:05,  4.34s/it]

Page 267: Found 34 satilir links (Total: 5679)

 91%|█████████ | 268/296 [19:46<01:59,  4.26s/it]

Page 268: Found 32 satilir links (Total: 5700)

 91%|█████████ | 269/296 [19:51<01:56,  4.30s/it]

Page 269: Found 32 satilir links (Total: 5721)

 91%|█████████ | 270/296 [19:56<01:54,  4.41s/it]

Page 270: Found 31 satilir links (Total: 5742)

 92%|█████████▏| 271/296 [20:00<01:47,  4.30s/it]

Page 271: Found 34 satilir links (Total: 5763)

 92%|█████████▏| 272/296 [20:04<01:43,  4.30s/it]

Page 272: Found 31 satilir links (Total: 5784)

 92%|█████████▏| 273/296 [20:08<01:39,  4.32s/it]

Page 273: Found 32 satilir links (Total: 5805)

 93%|█████████▎| 274/296 [20:12<01:34,  4.28s/it]

Page 274: Found 33 satilir links (Total: 5826)

 93%|█████████▎| 275/296 [20:17<01:31,  4.34s/it]

Page 275: Found 33 satilir links (Total: 5847)

 93%|█████████▎| 276/296 [20:23<01:36,  4.82s/it]

Page 276: Found 31 satilir links (Total: 5868)

 94%|█████████▎| 277/296 [20:28<01:34,  4.98s/it]

Page 277: Found 32 satilir links (Total: 5889)

 94%|█████████▍| 278/296 [20:33<01:26,  4.78s/it]

Page 278: Found 33 satilir links (Total: 5910)

 94%|█████████▍| 279/296 [20:37<01:19,  4.67s/it]

Page 279: Found 31 satilir links (Total: 5931)

 95%|█████████▍| 280/296 [20:42<01:18,  4.90s/it]

Page 280: Found 32 satilir links (Total: 5952)

 95%|█████████▍| 281/296 [20:46<01:10,  4.67s/it]

Page 281: Found 34 satilir links (Total: 5973)

 95%|█████████▌| 282/296 [20:51<01:04,  4.61s/it]

Page 282: Found 33 satilir links (Total: 5994)

 96%|█████████▌| 283/296 [20:55<00:58,  4.52s/it]

Page 283: Found 23 satilir links (Total: 6004)

 96%|█████████▌| 284/296 [21:01<00:57,  4.80s/it]

Page 284: Found 41 satilir links (Total: 6015)

 96%|█████████▋| 285/296 [21:06<00:53,  4.86s/it]

Page 285: Found 41 satilir links (Total: 6015)

 97%|█████████▋| 286/296 [21:11<00:48,  4.85s/it]

Page 286: Found 41 satilir links (Total: 6015)

 97%|█████████▋| 287/296 [21:15<00:43,  4.78s/it]

Page 287: Found 41 satilir links (Total: 6015)

 97%|█████████▋| 288/296 [21:20<00:38,  4.84s/it]

Page 288: Found 41 satilir links (Total: 6015)

 98%|█████████▊| 289/296 [21:25<00:34,  4.87s/it]

Page 289: Found 41 satilir links (Total: 6015)

 98%|█████████▊| 290/296 [21:30<00:29,  4.87s/it]

Page 290: Found 41 satilir links (Total: 6015)

 98%|█████████▊| 291/296 [21:35<00:24,  4.86s/it]

Page 291: Found 41 satilir links (Total: 6015)

 99%|█████████▊| 292/296 [21:39<00:19,  4.78s/it]

Page 292: Found 41 satilir links (Total: 6015)

 99%|█████████▉| 293/296 [21:44<00:14,  4.72s/it]

Page 293: Found 41 satilir links (Total: 6015)

 99%|█████████▉| 294/296 [21:49<00:09,  4.68s/it]

Page 294: Found 41 satilir links (Total: 6015)

100%|█████████▉| 295/296 [21:53<00:04,  4.67s/it]

Page 295: Found 41 satilir links (Total: 6015)

100%|██████████| 296/296 [21:58<00:00,  4.45s/it]

Page 296: Found 41 satilir links (Total: 6015)

✓ Scraping complete!
Total unique satilir links collected: 6015

In [ ]:
# Save links to CSV and display sample
df_links = pd.DataFrame({'url': all_satilir_links})
df_links.to_csv('satilir_links.csv', index=False)

In [ ]:
# Load the saved links
df_links = pd.read_csv('satilir_links.csv')
print(f"Loaded {len(df_links)} links to scrape")
print(df_links.head())

Loaded 6297 links to scrape
                                                 url
0  https://arenda.az/satilir-4-otaqli-heyet-evi-v...
1  https://arenda.az/satilir-3-otaqli-yeni-tikili...
2  https://arenda.az/satilir-2-otaqli-yeni-tikili...
3  https://arenda.az/satilir-7-otaqli-bag-evi-bin...
4  https://arenda.az/satilir-3-otaqli-yeni-tikili...

In [8]:
for i in range(len(df_links)):
    url = df_links.loc[i, 'url']
    print(f"{i+1}/{len(df_links)}: {url}")

1/6297: https://arenda.az/satilir-4-otaqli-heyet-evi-villa-abseron-rayonu-masazir-azer-city-kuc
2/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-xetai-rayonu-hezi-aslanov-metrosu-kohne-gunesli-qes-general-sixlinski-kucesi-4
3/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yeni-yasamal-qes-yeni-yasamal-qesebesi-mehemmed-xiyabani-kucesi-62
4/6297: https://arenda.az/satilir-7-otaqli-bag-evi-bineqedi-rayonu-avtovagzal-metrosu-bileceri-qes-baki-seheri-bineqedi-rayonu
5/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-baki-seheri-abseron-rayonu-4
6/6297: https://arenda.az/satilir-1-otaqli-yeni-tikili-abseron-rayonu-masazir-azadliq-pr-60
7/6297: https://arenda.az/satilir-5-otaqli-heyet-evi-villa-xezer-rayonu-merdekan-28-may-2
8/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-sabuncu-rayonu-bakixanov-qes-genclik-kuc-29-c-m-94
9/6297: https://arenda.az/satilir-3-otaqli-heyet-evi-villa-sabuncu-rayonu-zabrat-qes-sabuncu-rayonu-zabrat-qesebesinde-83
10/6297: https://arenda.az/satilir-4-otaqli-heyet-evi-villa-sabuncu-rayonu-ramana-qes-sabuncu-rayonu-ramana-qesebesinde-19
11/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-xetai-rayonu-hezi-aslanov-metrosu-ehmedli-mehemmed-hadi-kuc-40
12/6297: https://arenda.az/satilir-3-otaqli-kohne-tikili-xetai-rayonu-ehmedli-metrosu-ehmedli-seyid-ezim-sirvani-kuc-3
13/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-sumqayit-sumqayit-49
14/6297: https://arenda.az/satilir-5-otaqli-heyet-evi-villa-bineqedi-rayonu-azadliq-metrosu-bineqedi-qes-bineqedi-qesebesi-dircelis-kucesi-4
15/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-qurtulus93-15
16/6297: https://arenda.az/satilir-3-otaqli-heyet-evi-villa-qaradag-rayonu-lokbatan-qes-lokbatan-q-massiv-1-kuce-5-1
17/6297: https://arenda.az/satilir-2-otaqli-heyet-evi-villa-abseron-rayonu-masazir-masazir-421
18/6297: https://arenda.az/satilir-3-otaqli-kohne-tikili-yasamal-rayonu-insaatcilar-metrosu-serifzade-kucesi-83
19/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-xirdalan-baki-sumqayit-yolu-7ci-km-abweron-xestexanin-yani-korpu-bina-tikinti
20/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-nerimanov-rayonu-genclik-metrosu-hesen-eliyev-kucesi-30
21/6297: https://arenda.az/satilir-4-otaqli-heyet-evi-villa-xirdalan-xirdalan-dairesine-yaxin-17
22/6297: https://arenda.az/satilir-3-otaqli-heyet-evi-villa-xirdalan-xirdalan-seheri-826
23/6297: https://arenda.az/satilir-2-otaqli-heyet-evi-villa-xirdalan-xirdalan-seheri-409
24/6297: https://arenda.az/satilir-4-otaqli-heyet-evi-villa-xezer-rayonu-bine-qes-bine-qesebesi-590
25/6297: https://arenda.az/satilir-1-otaqli-heyet-evi-villa-xezer-rayonu-bine-qes-bine-qesebesi-75
26/6297: https://arenda.az/satilir-5-otaqli-kohne-tikili-suraxani-rayonu-yeni-gunesli-qes-suraxani-rayonu-yeni-gunesli-v-massivi-samir-ceferov-kuc
27/6297: https://arenda.az/satilir-3-otaqli-heyet-evi-villa-qaradag-rayonu-lokbatan-qes-hemid-sultanov
28/6297: https://arenda.az/satilir-3-otaqli-heyet-evi-villa-xezer-rayonu-bine-qes-bine-qesebesi-1967
29/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2845
30/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2711
31/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2806
32/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-qesebesi-2222
33/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yasamal-qes-zahid-xelilov-kucesi-1
34/6297: https://arenda.az/satilir-2-otaqli-kohne-tikili-suraxani-rayonu-suraxani-qes-suraxani-ray-yeni-genesli-v-massivi
35/6297: https://arenda.az/villa-satilir/
36/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-elmler-akademiyasi-metrosu-yasamal-qes-yasamal-qes-z-xelilov-kucesi-musabeyov-parkinin-yaxinligi
37/6297: https://arenda.az/satilir-10-otaqli-heyet-evi-villa-nerimanov-rayonu-genclik-metrosu-boyuksor-qes-genclikde-milyonerler-mehellesi
38/6297: https://arenda.az/satilir-5-otaqli-heyet-evi-villa-quba-qubanin-merkezinde-h-eliyev-prospekti
39/6297: https://arenda.az/satilir-torpaq-xezer-rayonu-suvelan-suvelanda-230-nomreli-mektebin-yaninda
40/6297: https://arenda.az/satilir-3-otaqli-heyet-evi-villa-sabuncu-rayonu-zabrat-qes-zabrat-qes-152
41/6297: https://arenda.az/satilir-4-otaqli-heyet-evi-villa-sabuncu-rayonu-koroglu-metrosu-zabrat-qes-zabrat-mehemmedli-yolu-22
42/6297: https://arenda.az/satilir-2-otaqli-kohne-tikili-nizami-rayonu-xalqlar-dostlugu-metrosu-8-ci-kilometr-behruz-nuriyev-kuc-14
43/6297: https://arenda.az/satilir-2-otaqli-kohne-tikili-xetai-rayonu-hezi-aslanov-metrosu-ehmedli-elcin-eliyev-kucesi
44/6297: https://arenda.az/satilir-14-otaqli-heyet-evi-villa-bineqedi-rayonu-8-ci-mikrorayon-cefer-xendan-kucesi
45/6297: https://arenda.az/satilir-obyekt-qaradag-rayonu-lokbatan-qes-lokbatan-qesebesi-1
46/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-abseron-rayon-masazir-qesebesi-qurtulus-93-yasayis-kompleksi-905
47/6297: https://arenda.az/satilir-3-otaqli-heyet-evi-villa-sabuncu-rayonu-savalan-qes-savalan-qesebesi-44
48/6297: https://arenda.az/satilir-1-otaqli-yeni-tikili-xirdalan-xirdalan-jasmin-park
49/6297: https://arenda.az/satilir-2-otaqli-kohne-tikili-yasamal-rayonu-elmler-akademiyasi-metrosu-yasamal-qes-mireli-seyidov-kucesi-16
50/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-xirdalan-xirdalan-s-blue-city-yasayis-kompleksi-2
51/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2703
52/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-1597
53/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2574
54/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-1679
55/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2763
56/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2760
57/6297: https://arenda.az/satilir-2-otaqli-heyet-evi-villa-xezer-rayonu-bine-qes-bine-qes-18
58/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-1706
59/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-1714
60/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2851
61/6297: https://arenda.az/satilir-6-otaqli-heyet-evi-villa-abseron-rayonu-masazir-abseron-rayon-masazir-qesebesi-51
62/6297: https://arenda.az/satilir-3-otaqli-heyet-evi-villa-xezer-rayonu-bine-qes-bine-qes-181
63/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-1691
64/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-xirdalan-qalibiyye-kucesi-10
65/6297: https://arenda.az/satilir-3-otaqli-heyet-evi-villa-xezer-rayonu-bine-qes-bine-qesebesi-1966
66/6297: https://arenda.az/satilir-4-otaqli-heyet-evi-villa-xezer-rayonu-bine-qes-bine-qes-73
67/6297: https://arenda.az/novxanida-torpaq-satilir/
68/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-xetai-rayonu-hezi-aslanov-metrosu-xudu-memmedov-kuc-213
69/6297: https://arenda.az/satilir-4-otaqli-yeni-tikili-nerimanov-rayonu-genclik-metrosu-ceyhun-hacibeyli-kc
70/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-xirdalan-xirdalan-4086
71/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-67
72/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-1559
73/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2849
74/6297: https://arenda.az/satilir-3-otaqli-heyet-evi-villa-xezer-rayonu-bine-qes-bine-qesebesi-1965
75/6297: https://arenda.az/satilir-1-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-478
76/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-xirdalan-xirdalan-4085
77/6297: https://arenda.az/satilir-2-otaqli-kohne-tikili-suraxani-rayonu-yeni-gunesli-qes-suraxani-r-yeni-gunesli-qes-v-massivi
78/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-xirdalan-h-eliyev-prospekti-406
79/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-xirdalan-xirdalan-aaaf-park-144
80/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-xetai-rayonu-ehmedli-metrosu-asiq-elesger-kuc-4
81/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-ebdulvahab-salamzade-kucesi-21
82/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-xetai-rayonu-hezi-aslanov-metrosu-ehmedli-sadiqcan-kucesi-52
83/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-xirdalan-xirdalan-s-blue-city-yasayis-kompleksi-1
84/6297: https://arenda.az/satilir-5-otaqli-yeni-tikili-nesimi-rayonu-8-noyabr-metrosu-hesen-eliyev-kuc-2
85/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-abseron-rayon-masazir-qesebesi-qurtulus-93-yasayis-kompleksi-852
86/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yeni-yasamal-qes-musteqillik-kucesi-12
87/6297: https://arenda.az/satilir-4-otaqli-yeni-tikili-xetai-rayonu-ehmedli-gence-prospekti
88/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-mehemmedli-abseron-rayonu-mehemmedli-qesebesi-17
89/6297: https://arenda.az/hovsanda-torpaq-satilir/
90/6297: https://arenda.az/2-otaqli-menziller-satilir/
91/6297: https://arenda.az/genclik-tecili-ev-satilir/
92/6297: https://arenda.az/satilir-2-otaqli-kohne-tikili-suraxani-rayonu-yeni-gunesli-qes-yeni-gunesli-qesebesi-46
93/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yeni-yasamal-qes-mida-yasayis-kompleksi-42
94/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-xetai-rayonu-ehmedli-metrosu-ehmedli-lutfizade-kucesi-26
95/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-yasamal-qes-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksi-1
96/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksi-1
97/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-yasamal-qes-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksi
98/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-suraxani-rayonu-yeni-gunesli-qes-yeni-gunesli-d-massivi-kiristal-apseron-290-nomreli-mektebin-yani
99/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-yasamal-rayonu-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksinin-insa-etdiyi-park-yasamal
100/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-yasamal-qes-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksi-4
101/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-yasamal-qes-yasamal-rayonu-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksinin-insa-etdiyi-park-yasamal-2
102/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-yasamal-qes-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksi
103/6297: https://arenda.az/satilir-3-otaqli-kohne-tikili-xetai-rayonu-ehmedli-metrosu-ehmedli-xetai-rayonu-ehmedli-qesebesi-ehmedli-metrosu-yaxinligi
104/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-yasamal-rayonu-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksinin-insa-etdiyi-park-yasamal-l
105/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksi
106/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksi
107/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-yasamal-qes-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksi-2
108/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-yasamal-qes-yasamal-rayonu-park-yasamal-2kiristal-apseron
109/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-yasamal-qes-yasamal-rayonu-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksinin-insa-etdiyi-park-yasamal
110/6297: https://arenda.az/satilir-4-otaqli-kohne-tikili-suraxani-rayonu-yeni-gunesli-qes-suraxani-rayonu-yeni-gunesli-qes-qartal-heykeli-yaxinligi-ab-massivi
111/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-yasamal-qes-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksi-3
112/6297: https://arenda.az/satilir-4-otaqli-yeni-tikili-xetai-rayonu-hezi-aslanov-metrosu-ehmedli-gence-prospekti-29-35-2
113/6297: https://arenda.az/1-otaqli-ev-satilir/
114/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-yasamal-qes-asan-xidmetin-arxasi-kristal-abseron-yasayis-kompleksi-1
115/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-xetai-rayonu-h-aslanov-qes-xetai-rayonu-gence-prospekti-xetai-park-yasayis-kompleksi-1
116/6297: https://arenda.az/satilir-5-otaqli-heyet-evi-villa-suraxani-rayonu-bulbule-qes-suraxani-rayonu-bulbule-qesebesi-aeroport-yolunun-kenari
117/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yeni-yasamal-qes-dadas-bunyadzade-135
118/6297: https://arenda.az/satilir-2-otaqli-kohne-tikili-nerimanov-rayonu-neriman-nerimanov-metrosu-nerimnov-rayonu-nerimanov-metrosu-esref-eliyev-kucesi-qoc-etin-yani
119/6297: https://arenda.az/satilir-4-otaqli-yeni-tikili-sebail-rayonu-iceriseher-metrosu-badamdar-qes-abbasqulu-abbaszade-kuc
120/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yasamal-rayonu-hesen-bey-zerdabi-kucesi-insatcilar-metrosu-yaxinligi
121/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-nesimi-rayonu-28-may-metrosu-mixail-kaverockin-kucesi
122/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-masazir-abseron-rayon-masazir-qesebesi-qurtulus-93-yasayis-kompleksi-428
123/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-st-sumqayit-rayonu-sumqayit-seh-23
124/6297: https://arenda.az/satilir-2-otaqli-kohne-tikili-xetai-rayonu-ehmedli-metrosu-ehmedli-sarayeva-kucesi-18
125/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-xetai-rayonu-hezi-aslanov-metrosu-sadiqcan-kucesi-71
126/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-saray-saray-mtk-23
127/6297: https://arenda.az/satilir-4-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yeni-yasamal-qes-mida-yasayis-kompleksi-12
128/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-suraxani-rayonu-yeni-gunesli-qes-yeni-gunesli-d-massiv-2
129/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-bineqedi-rayonu-7-ci-mikrorayon-west-town-2
130/6297: https://arenda.az/satilir-10-otaqli-heyet-evi-villa-gence-puskin-kuc-ev-8
131/6297: https://arenda.az/satilir-1-otaqli-yeni-tikili-sabuncu-rayonu-nardaran-qes-sea-breeze-24
132/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-suraxani-rayonu-qaracuxur-qes-qaracuxur-qesebesi-19
133/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-masazir-2742
134/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-kenar-dairevi-7-1
135/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-nerimanov-rayonu-genclik-metrosu-balaemi-dadasov-kucesi-2
136/6297: https://arenda.az/satilir-4-otaqli-kohne-tikili-xetai-rayonu-hezi-aslanov-metrosu-kohne-gunesli-qes-hezi-aslanov
137/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-st-sumqayit-rayonu-sumqayit-seh-24
138/6297: https://arenda.az/satilir-3-otaqli-kohne-tikili-suraxani-rayonu-yeni-gunesli-qes-yeni-gunesli-ab-massivi-56
139/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-xirdalan-aaaf-parkda-27
140/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-xirdalan-aaaf-park-yasayis-kompleksi-550
141/6297: https://arenda.az/satilir-3-otaqli-kohne-tikili-nizami-rayonu-8-ci-kilometr-qara-qarayev
142/6297: https://arenda.az/satilir-3-otaqli-kohne-tikili-xetai-rayonu-hezi-aslanov-metrosu-kohne-gunesli-qes-general-eliaga-sixlinski-kucesi-3
143/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yeni-yasamal-qes-musteqillik-kucesi-11
144/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-nesimi-rayonu-28-may-metrosu-samil-eziizbeyov-kucesi-201
145/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-bineqedi-rayonu-dernegul-metrosu-7-ci-mikrorayon-dernegul-metrosunun-cixisi-cefer-xendan-kuc-west-town-yasayis-kompleksinde-5
146/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yeni-yasamal-qes-musteqillik-kucesi-10
147/6297: https://arenda.az/satilir-1-otaqli-yeni-tikili-abseron-rayonu-saray-saray-mtk-8
148/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-xetai-rayonu-ehmedli-metrosu-ehmedli-mehemmed-hadi-kucesi-97
149/6297: https://arenda.az/satilir-5-otaqli-heyet-evi-villa-xezer-rayonu-merdekan-4
150/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-saray-saray-106
151/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-saray-saray-mtk-137
152/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yeni-yasamal-qes-musteqillik-kucesi-9
153/6297: https://arenda.az/satilir-4-otaqli-heyet-evi-villa-xezer-rayonu-musa-nagiyev
154/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yeni-yasamal-qes-musteqillik-kucesi-8
155/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-eliaga-vahid-kucesi-673
156/6297: https://arenda.az/merdekanda-torpaq-satilir/
157/6297: https://arenda.az/digahda-torpaq-satilir/
158/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-eliaga-vahid-kucesi-672
159/6297: https://arenda.az/satilir-6-otaqli-heyet-evi-villa-abseron-rayonu-novxani-novxani-qesebesi-37
160/6297: https://arenda.az/satilir-6-otaqli-heyet-evi-villa-sabuncu-rayonu-bakixanov-qes-mehseti-gencevi-kucesi
161/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-abseron-rayonu-masazir-eliaga-vahid-kucesi-674
162/6297: https://arenda.az/satilir-3-otaqli-kohne-tikili-nizami-rayonu-qara-qarayev-metrosu-tofiq-abbasov-kucesi-12
163/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-yasamal-rayonu-20-yanvar-metrosu-main-mtk
164/6297: https://arenda.az/satilir-6-otaqli-heyet-evi-villa-qaradag-rayonu-lokbatan-qes-lokbatan-qesebesi-4-cu-massiv-2-ci-kecid-ev-2
165/6297: https://arenda.az/satilir-4-otaqli-heyet-evi-villa-abseron-rayonu-masazir-eliaga-vahid-kucesi-37
166/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-nesimi-rayonu-28-may-metrosu-salatin-esgerov-kuc
167/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yeni-yasamal-qes-yasamal-rayonu-yeni-yasamal-qesebesi-mehemmed-xiyabani-kucesi-81
168/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-nerimanov-rayonu-neriman-nerimanov-metrosu-n-nerimanov-4
169/6297: https://arenda.az/satilir-4-otaqli-yeni-tikili-xetai-rayonu-baki-aq-seher
170/6297: https://arenda.az/satilir-1-otaqli-kohne-tikili-nerimanov-rayonu-genclik-metrosu-genclik-m-k-rehimov-kuc
171/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-nesimi-rayonu-28-may-metrosu-mireli-qasqay-kuc-77
172/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-yasamal-rayonu-insaatcilar-metrosu-yeni-yasamal-qes-musteqillik-kucesi-13
173/6297: https://arenda.az/satilir-2-otaqli-heyet-evi-villa-abseron-rayonu-masazir-eliaga-vahid-kuc-1117
174/6297: https://arenda.az/satilir-4-otaqli-kohne-tikili-xetai-rayonu-hezi-aslanov-metrosu-kohne-gunesli-qes-general-eliaga-sixlinski-kucesi-1
175/6297: https://arenda.az/satilir-7-otaqli-yeni-tikili-nerimanov-rayonu-neriman-nerimanov-metrosu-tebriz-kucesi-1
176/6297: https://arenda.az/satilir-2-otaqli-yeni-tikili-sumqayit-bulvari-rayonu-beyaz-residence-5
177/6297: https://arenda.az/satilir-3-otaqli-kohne-tikili-sabuncu-rayonu-bakixanov-qes-sulh-kucesi-46
178/6297: https://arenda.az/satilir-3-otaqli-yeni-tikili-abseron-rayonu-mehemmedli-zabrat-soesi-7
179/6297: https://arenda.az/satilir-4-otaqli-yeni-tikili-nesimi-rayonu-tibliski

## 3) Property Feature Extraction
Define helper functions and scrape base fields + dynamic amenities from each listing page.

**Output:** `satilir_properties_dynamic1.csv`

In [ ]:
# Iterate through saved links and extract base + dynamic features (Yes/No)

def _clean_text(text):
    return re.sub(r"\s+", " ", (text or "")).strip()


def _to_feature_key(text):
    # Normalize Azerbaijani chars for stable column names
    txt = _clean_text(text).lower()
    translit = {
        "ə": "e", "ö": "o", "ğ": "g", "ü": "u", "ı": "i", "ş": "s", "ç": "c",
        "Ə": "e", "Ö": "o", "Ğ": "g", "Ü": "u", "İ": "i", "Ş": "s", "Ç": "c",
    }
    for k, v in translit.items():
        txt = txt.replace(k, v)
    txt = txt.replace("/", " ")
    txt = re.sub(r"[^a-z0-9\s]", "", txt)
    txt = re.sub(r"\s+", "_", txt).strip("_")
    return txt


def _extract_number(text):
    if not text:
        return None
    m = re.search(r"(\d+(?:[\.,]\d+)?)", text)
    if not m:
        return None
    n = m.group(1).replace(",", ".")
    return float(n) if "." in n else int(n)


def _extract_base_fields(bs):
    rec = {
        "price": None,
        "rooms": None,
        "area_m2": None,
        "land_area_sot": None,
        "floor": None,
        "has_document": None,
        "address": None,
    }

    # Price
    price_box = bs.select_one("div.elan_new_price_box p")
    if price_box:
        ptxt = _clean_text(price_box.get_text(" ", strip=True))
        m = re.search(r"(\d[\d\s]*)", ptxt)
        if m:
            rec["price"] = int(m.group(1).replace(" ", ""))

    # Main attributes list
    main_items = [_clean_text(li.get_text(" ", strip=True)) for li in bs.select("ul.full.elan_property_list li")]
    for item in main_items:
        low = item.lower()
        low_compact = re.sub(r"\s+", "", low.replace("\xa0", " "))

        if rec["rooms"] is None and "otaq" in low:
            rec["rooms"] = _extract_number(low)

        if rec["area_m2"] is None and (
            "m²" in low or "m2" in low_compact or "kv.m" in low or "kvm" in low_compact
            or "sahə" in low or "sahe" in low
        ):
            rec["area_m2"] = _extract_number(low)
            if rec["area_m2"] is None:
                m_area = re.search(r"(\d+(?:[\.,]\d+)?)\s*(?:m²|m2|kv\.?m)", low)
                if m_area:
                    n = m_area.group(1).replace(",", ".")
                    rec["area_m2"] = float(n) if "." in n else int(n)

        if rec["land_area_sot"] is None and "sot" in low:
            rec["land_area_sot"] = _extract_number(low)

        if rec["floor"] is None and ("mərtəb" in low or "merteb" in low):
            rec["floor"] = _extract_number(low)

        if any(x in low for x in ["kupça", "kupca", "çıxarış", "cixaris"]):
            rec["has_document"] = "Yes"

    if rec["has_document"] is None:
        rec["has_document"] = "No"

    # Address
    address_parts = [_clean_text(li.get_text(" ", strip=True)) for li in bs.select("ul.elan_adr_list.full li")]
    rec["address"] = ", ".join([x for x in address_parts if x]) if address_parts else None

    return rec

In [ ]:
# Determine which column contains links
link_col = "url" if "url" in df_links.columns else ("link" if "link" in df_links.columns else df_links.columns[0])
urls = df_links[link_col].dropna().astype(str).tolist()[:1000]  # First 50 links only

all_records = []
all_features = []  # ordered global list of discovered dynamic features

for i, url in enumerate(tqdm(urls), 1):
    driver.get(url)
    time.sleep(1.5)
    bs = BeautifulSoup(driver.page_source, "html.parser")

    rec = {"link": url}
    rec.update(_extract_base_fields(bs))

    # Additional features section
    # If section missing => all known features should be No
    feature_lis = bs.select("ul.full.property_lists li")
    current_features = set()

    for li in feature_lis:
        ftxt = _clean_text(li.get_text(" ", strip=True))
        if not ftxt:
            continue
        fkey = _to_feature_key(ftxt)
        if not fkey:
            continue

        current_features.add(fkey)

        # New feature found: add globally + backfill old records with No
        if fkey not in all_features:
            all_features.append(fkey)
            for prev in all_records:
                prev[fkey] = "No"

    # Mark Yes/No for ALL known features
    for f in all_features:
        rec[f] = "Yes" if f in current_features else "No"

    all_records.append(rec)

# Final DataFrame
df_properties_dynamic = pd.DataFrame(all_records)

# Keep base columns first, then dynamic feature columns
base_cols = ["link", "price", "rooms", "area_m2", "land_area_sot", "floor", "has_document", "address"]
feature_cols = [c for c in all_features if c in df_properties_dynamic.columns]
ordered_cols = [c for c in base_cols if c in df_properties_dynamic.columns] + feature_cols

df_properties_dynamic = df_properties_dynamic[ordered_cols]

print(f"Done. Listings scraped: {len(df_properties_dynamic)}")
print(f"Dynamic features discovered: {len(feature_cols)}")
print(f"\nFeatures found: {feature_cols}")
print(f"\nFirst 5 listings:")
df_properties_dynamic.head()

  0%|          | 0/1000 [00:00<?, ?it/s]

100%|██████████| 1000/1000 [1:08:49<00:00,  4.13s/it]

Done. Listings scraped: 1000
Dynamic features discovered: 19

Features found: ['temirli', 'qaz', 'su', 'isiq', 'avtodayanacaq', 'telefon', 'internet', 'pvc_pencere', 'balkon', 'kabel_tv', 'lift', 'kombi', 'metbex_mebeli', 'temirsiz', 'merkezi_qizdirici_sistem', 'kondisioner', 'esyali', 'hovuz', 'duzelme']

First 5 listings:

,link,price,rooms,area_m2,land_area_sot,floor,has_document,address,temirli,qaz,...,kabel_tv,lift,kombi,metbex_mebeli,temirsiz,merkezi_qizdirici_sistem,kondisioner,esyali,hovuz,duzelme
0,https://arenda.az/satilir-4-otaqli-heyet-evi-v...,115000.0,4.0,130.0,1.3,2.0,Yes,"Bakı, Abşeron, Masazır",Yes,Yes,...,No,No,No,No,No,No,No,No,No,No
1,https://arenda.az/satilir-3-otaqli-yeni-tikili...,195500.0,3.0,86.0,NaN,6.0,Yes,"Bakı, Xətai, Köhnə Günəşli qəs., metro Həzi As...",Yes,Yes,...,Yes,Yes,Yes,Yes,No,No,No,No,No,No
2,https://arenda.az/satilir-2-otaqli-yeni-tikili...,55000.0,2.0,78.0,NaN,4.0,Yes,"Bakı, Yasamal, Yeni Yasamal qəs., metro İnşaat...",No,No,...,No,No,No,No,No,No,No,No,No,No
3,https://arenda.az/satilir-7-otaqli-bag-evi-bin...,200000.0,7.0,NaN,4.0,2.0,No,"Bakı, Binəqədi, Biləcəri qəs., metro Avtovağzal",No,No,...,No,No,No,No,No,No,No,No,No,No
4,https://arenda.az/satilir-3-otaqli-yeni-tikili...,97000.0,3.0,92.0,NaN,8.0,No,"Bakı, Abşeron, Masazır",No,No,...,No,No,No,No,No,No,No,No,No,No

In [29]:
df_properties_dynamic.to_csv("satilir_properties_dynamic1.csv", index=False)

## 4) Large-Range Scraping + Image Download
This step scrapes listings from index **5500 to the end**, extracts dynamic features, and downloads gallery images into local folders.

Because of repeated crashes during long runs, the full scraping job was split into batches. The range from index **0 to 5499** was completed earlier, and this section processes only the remaining listings.

### Outputs
- `satilir_properties_5500_end_with_photos.csv`
- `satilir_photos_5500_end/` (downloaded images per listing folder)

In [ ]:
# NEW CODE: links 5500 to end + dynamic features + save photos

# --- make this cell self-contained (in case helper cell wasn't run) ---
if "_clean_text" not in globals():
    def _clean_text(text):
        return re.sub(r"\s+", " ", (text or "")).strip()

if "_to_feature_key" not in globals():
    def _to_feature_key(text):
        txt = _clean_text(text).lower()
        translit = {
            "ə": "e", "ö": "o", "ğ": "g", "ü": "u", "ı": "i", "ş": "s", "ç": "c",
            "Ə": "e", "Ö": "o", "Ğ": "g", "Ü": "u", "İ": "i", "Ş": "s", "Ç": "c",
        }
        for k, v in translit.items():
            txt = txt.replace(k, v)
        txt = txt.replace("/", " ")
        txt = re.sub(r"[^a-z0-9\s]", "", txt)
        txt = re.sub(r"\s+", "_", txt).strip("_")
        return txt

if "_extract_number" not in globals():
    def _extract_number(text):
        if not text:
            return None
        m = re.search(r"(\d+(?:[\.,]\d+)?)", text)
        if not m:
            return None
        n = m.group(1).replace(",", ".")
        return float(n) if "." in n else int(n)

if "_extract_base_fields" not in globals():
    def _extract_base_fields(bs):
        rec = {
            "price": None,
            "rooms": None,
            "area_m2": None,
            "land_area_sot": None,
            "floor": None,
            "has_document": None,
            "address": None,
        }

        price_box = bs.select_one("div.elan_new_price_box p")
        if price_box:
            ptxt = _clean_text(price_box.get_text(" ", strip=True))
            m = re.search(r"(\d[\d\s]*)", ptxt)
            if m:
                rec["price"] = int(m.group(1).replace(" ", ""))

        main_items = [_clean_text(li.get_text(" ", strip=True)) for li in bs.select("ul.full.elan_property_list li")]
        for item in main_items:
            low = item.lower()
            low_compact = re.sub(r"\s+", "", low.replace("\xa0", " "))

            if rec["rooms"] is None and "otaq" in low:
                rec["rooms"] = _extract_number(low)

            if rec["area_m2"] is None and (
                "m²" in low or "m2" in low_compact or "kv.m" in low or "kvm" in low_compact
                or "sahə" in low or "sahe" in low
            ):
                rec["area_m2"] = _extract_number(low)
                if rec["area_m2"] is None:
                    m_area = re.search(r"(\d+(?:[\.,]\d+)?)\s*(?:m²|m2|kv\.?m)", low)
                    if m_area:
                        n = m_area.group(1).replace(",", ".")
                        rec["area_m2"] = float(n) if "." in n else int(n)

            if rec["land_area_sot"] is None and "sot" in low:
                rec["land_area_sot"] = _extract_number(low)

            if rec["floor"] is None and ("mərtəb" in low or "merteb" in low):
                rec["floor"] = _extract_number(low)

            if any(x in low for x in ["kupça", "kupca", "çıxarış", "cixaris"]):
                rec["has_document"] = "Yes"

        if rec["has_document"] is None:
            rec["has_document"] = "No"

        address_parts = [_clean_text(li.get_text(" ", strip=True)) for li in bs.select("ul.elan_adr_list.full li")]
        rec["address"] = ", ".join([x for x in address_parts if x]) if address_parts else None

        return rec


def _extract_gallery_urls(bs):
    urls = []
    gallery = bs.select_one("div.property-gallery")
    if not gallery:
        return urls

    for a in gallery.select('a[data-fancybox="gallery"][href]'):
        href = (a.get("href") or "").strip()
        if not href:
            continue
        if href.startswith("//"):
            href = "https:" + href
        elif href.startswith("/"):
            href = "https://arenda.az" + href
        if href.startswith("http") and href not in urls:
            urls.append(href)

    return urls


def _download_images(image_urls, listing_dir):
    listing_dir.mkdir(parents=True, exist_ok=True)
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36",
        "Referer": "https://arenda.az/"
    }

    saved_paths = []
    for j, img_url in enumerate(image_urls, 1):
        try:
            parsed = urlparse(img_url)
            ext = os.path.splitext(parsed.path)[1].lower()
            if ext not in [".jpg", ".jpeg", ".png", ".webp", ".gif"]:
                ext = ".jpg"

            file_path = listing_dir / f"img_{j:03d}{ext}"
            r = requests.get(img_url, headers=headers, timeout=30)
            if r.status_code == 200 and r.content:
                with open(file_path, "wb") as f:
                    f.write(r.content)
                saved_paths.append(str(file_path))
        except Exception:
            continue

    return saved_paths


# links 5500th to end (1-based indexing)
start_idx = 5499

link_col = "url" if "url" in df_links.columns else ("link" if "link" in df_links.columns else df_links.columns[0])
urls = df_links[link_col].dropna().astype(str).tolist()[start_idx:]

photos_root = Path("satilir_photos_5500_end")
photos_root.mkdir(parents=True, exist_ok=True)

all_records = []
all_features = []

for i, url in enumerate(tqdm(urls, desc="Scraping links 5500-end"), start_idx + 1):
    try:
        driver.get(url)
        time.sleep(1.5)
        bs = BeautifulSoup(driver.page_source, "html.parser")

        rec = {"link": url}
        rec.update(_extract_base_fields(bs))

        # dynamic features yes/no
        feature_lis = bs.select("ul.full.property_lists li")
        current_features = set()

        for li in feature_lis:
            ftxt = _clean_text(li.get_text(" ", strip=True))
            if not ftxt:
                continue
            fkey = _to_feature_key(ftxt)
            if not fkey:
                continue

            current_features.add(fkey)
            if fkey not in all_features:
                all_features.append(fkey)
                for prev in all_records:
                    prev[fkey] = "No"

        for f in all_features:
            rec[f] = "Yes" if f in current_features else "No"

        # photos
        image_urls = _extract_gallery_urls(bs)
        listing_slug = re.sub(r"[^a-zA-Z0-9_-]", "_", url.rstrip("/").split("/")[-1])
        listing_dir = photos_root / f"{i:04d}_{listing_slug}"
        saved_paths = _download_images(image_urls, listing_dir)

        rec["photo_count"] = len(saved_paths)
        rec["photo_files"] = " | ".join(saved_paths) if saved_paths else None
        rec["photo_urls"] = " | ".join(image_urls) if image_urls else None

        all_records.append(rec)

    except Exception as e:
        rec = {
            "link": url,
            "price": None,
            "rooms": None,
            "area_m2": None,
            "land_area_sot": None,
            "floor": None,
            "has_document": None,
            "address": None,
            "photo_count": 0,
            "photo_files": None,
            "photo_urls": None,
            "error": str(e)
        }
        for f in all_features:
            rec[f] = "No"
        all_records.append(rec)

# final dataframe
base_cols = [
    "link", "price", "rooms", "area_m2", "land_area_sot", "floor",
    "has_document", "address", "photo_count", "photo_files", "photo_urls"
]

df_properties_with_photos_5500_end = pd.DataFrame(all_records)
feature_cols = [c for c in all_features if c in df_properties_with_photos_5500_end.columns]
other_cols = [c for c in df_properties_with_photos_5500_end.columns if c not in base_cols + feature_cols]
ordered_cols = [c for c in base_cols if c in df_properties_with_photos_5500_end.columns] + feature_cols + other_cols

df_properties_with_photos_5500_end = df_properties_with_photos_5500_end[ordered_cols]

df_properties_with_photos_5500_end.to_csv("satilir_properties_5500_end_with_photos.csv", index=False)

print(f"Done. Listings scraped: {len(df_properties_with_photos_5500_end)}")
print(f"Dynamic features discovered: {len(feature_cols)}")
print(f"Photos downloaded: {int(df_properties_with_photos_5500_end['photo_count'].fillna(0).sum())}")
print("CSV saved: satilir_properties_5500_end_with_photos.csv")
print("Images folder: satilir_photos_5500_end/")

df_properties_with_photos_5500_end.head()

Scraping links 5500-end: 100%|██████████| 798/798 [59:12<00:00,  4.45s/it]

Done. Listings scraped: 798
Dynamic features discovered: 19
Photos downloaded: 9944
CSV saved: satilir_properties_5500_end_with_photos.csv
Images folder: satilir_photos_5500_end/

,link,price,rooms,area_m2,land_area_sot,floor,has_document,address,photo_count,photo_files,...,metbex_mebeli,esyali,avtodayanacaq,temirsiz,lift,kombi,duzelme,merkezi_qizdirici_sistem,hovuz,telefon
0,https://arenda.az/satilir-2-otaqli-kohne-tikil...,127500.0,2.0,50.0,NaN,2.0,Yes,"Bakı, Nəsimi, 5-ci mikrorayon, metro Memar Əcəmi",15,satilir_photos_5500_end/5500_satilir-2-otaqli-...,...,Yes,Yes,Yes,No,No,No,No,No,No,No
1,https://arenda.az/satilir-2-otaqli-yeni-tikili...,10000.0,2.0,50.0,NaN,1.0,Yes,"Bakı, Abşeron, Masazır",4,satilir_photos_5500_end/5501_satilir-2-otaqli-...,...,Yes,No,Yes,No,No,No,No,No,No,No
2,https://arenda.az/satilir-2-otaqli-yeni-tikili...,NaN,NaN,NaN,NaN,NaN,No,None,0,None,...,No,No,No,No,No,No,No,No,No,No
3,https://arenda.az/satilir-2-otaqli-yeni-tikili...,10000.0,2.0,50.0,NaN,1.0,Yes,"Bakı, Abşeron, Masazır",5,satilir_photos_5500_end/5503_satilir-2-otaqli-...,...,Yes,No,Yes,No,No,No,No,No,No,No
4,https://arenda.az/satilir-2-otaqli-yeni-tikili...,163000.0,2.0,55.0,NaN,3.0,Yes,"Bakı, Binəqədi, 9-cu mikrorayon, metro Memar Ə...",15,satilir_photos_5500_end/5504_satilir-2-otaqli-...,...,No,No,No,No,No,No,No,No,No,No

## 5) Dataset Consolidation
Concatenate batch CSV files, align columns, and export one unified dataset.

**Output:** `satilir_properties.csv`

In [ ]:
# Concatenate "(Copy)" CSV files in the required order and save as satilir_properties.csv

# Required file order (prefix-based)
required_prefix_order = [
    "satilir_properties_1000",
    "satilir_properties_1000_2000",
    "satilir_properties_2000_3000",
    "satilir_properties_3000_4500",
    "satilir_properties_4500_5500",
    "satilir_properties_5500_end",
]

# Collect only CSV files that contain "(Copy)" in filename
all_csvs = [p for p in Path('.').glob('*.csv') if '(Copy)' in p.name]

def _order_key(path_obj):
    name = path_obj.stem  # filename without .csv
    # Primary ordering by required prefix sequence
    for idx, pref in enumerate(required_prefix_order):
        if name.startswith(pref):
            return (idx, name.lower())
    # Non-matching files go to end
    return (999, name.lower())

# Keep only files that match required prefixes
selected_files = [
    p for p in all_csvs
    if any(p.stem.startswith(pref) for pref in required_prefix_order)
]
selected_files = sorted(selected_files, key=_order_key)

if not selected_files:
    print('No matching "(Copy)" files found for required satilir_properties_* pattern.')
else:
    print('Files to concatenate (in order):')
    for i, f in enumerate(selected_files, 1):
        print(f'{i}. {f.name}')

    dfs = [pd.read_csv(f, low_memory=False) for f in selected_files]
    merged = pd.concat(dfs, ignore_index=True, sort=False)

    # Reorder columns to fix mixed feature order across files
    base_cols = [
        'link', 'price', 'rooms', 'area_m2', 'land_area_sot', 'floor',
        'has_document', 'address', 'photo_count', 'photo_files', 'photo_urls'
    ]
    trailing_known = ['error']

    existing_base = [c for c in base_cols if c in merged.columns]
    existing_trailing = [c for c in trailing_known if c in merged.columns]

    # Everything else treated as dynamic feature columns and sorted for consistency
    feature_cols = [
        c for c in merged.columns
        if c not in set(existing_base + existing_trailing)
    ]
    feature_cols = sorted(feature_cols)

    final_cols = existing_base + feature_cols + existing_trailing
    merged = merged[final_cols]

    output_file = 'satilir_properties.csv'
    merged.to_csv(output_file, index=False)

    print(f'\nDone. Rows: {len(merged)}')
    print(f'Columns: {len(merged.columns)}')
    print(f'Saved: {output_file}')
    merged.head()

Files to concatenate (in order):
1. satilir_properties_1000_2000_with_photos (Copy).csv
2. satilir_properties_1000_with_photos (Copy).csv
3. satilir_properties_2000_3000_with_photos (Copy).csv
4. satilir_properties_3000_4500_with_photos (Copy).csv
5. satilir_properties_4500_5500_with_photos (Copy).csv
6. satilir_properties_5500_end_with_photos (Copy).csv

Done. Rows: 6260
Columns: 28
Saved: satilir_properties.csv

In [31]:
df_final = pd.read_csv('satilir_properties.csv', low_memory=False)

## 6) Data Quality Checks
Validate data quality before modeling:
- remove rows with missing `price`
- remove duplicates
- save cleaned table back to disk

In [20]:
df_final['price'].isna().sum()

75

In [21]:
if 'df_final' not in globals():
    df_final = pd.read_csv('satilir_properties.csv', low_memory=False)

before_rows = len(df_final)
df_final = df_final[df_final['price'].notna()].copy()
after_rows = len(df_final)
deleted_rows = before_rows - after_rows

df_final.to_csv('satilir_properties.csv', index=False)

In [22]:
df_final.duplicated().sum()

2

In [26]:
df_final[df_final.duplicated(keep=False)]

,link,price,rooms,area_m2,land_area_sot,floor,has_document,address,avtodayanacaq,balkon,...,lift,merkezi_qizdirici_sistem,metbex_mebeli,pvc_pencere,qaz,su,telefon,temirli,temirsiz,error
999,https://arenda.az/satilir-8-otaqli-heyet-evi-v...,450000.0,8.0,250.0,7.0,2.0,Yes,"Bakı, Sabunçu, Yeni Ramana",Yes,Yes,...,No,No,Yes,Yes,Yes,Yes,No,Yes,No,NaN
1961,https://arenda.az/satilir-8-otaqli-heyet-evi-v...,450000.0,8.0,250.0,7.0,2.0,Yes,"Bakı, Sabunçu, Yeni Ramana",Yes,Yes,...,No,No,Yes,Yes,Yes,Yes,No,Yes,No,NaN
5461,https://arenda.az/satilir-2-otaqli-kohne-tikil...,127500.0,2.0,50.0,NaN,2.0,Yes,"Bakı, Nəsimi, 5-ci mikrorayon, metro Memar Əcəmi",Yes,Yes,...,No,No,Yes,Yes,Yes,Yes,No,Yes,No,NaN
5462,https://arenda.az/satilir-2-otaqli-kohne-tikil...,127500.0,2.0,50.0,NaN,2.0,Yes,"Bakı, Nəsimi, 5-ci mikrorayon, metro Memar Əcəmi",Yes,Yes,...,No,No,Yes,Yes,Yes,Yes,No,Yes,No,NaN

In [27]:
df_final = df_final.drop_duplicates()

In [28]:
df_final.to_csv('satilir_properties.csv', index=False)

In [32]:
df_final.isnull().sum()

link                           0
price                          0
rooms                          2
area_m2                      260
land_area_sot               4987
floor                          2
has_document                   0
address                        0
avtodayanacaq                  0
balkon                         0
duzelme                        0
esyali                         0
hovuz                          0
internet                       0
isiq                           0
kabel_tv                       0
kombi                          0
kondisioner                    0
lift                           0
merkezi_qizdirici_sistem       0
metbex_mebeli                  0
pvc_pencere                    0
qaz                            0
su                             0
telefon                        0
temirli                        0
temirsiz                       0
dtype: int64

## 7) Image Folder to Price Mapping
Match image folder names to listing slugs and generate a consolidated ID-price mapping table.

**Output:** `satilir_id_price_folder_all.csv`

In [ ]:
base_dir = Path('/home/admin123/AI_project')

# Map each photos folder to its corresponding CSV
folder_csv_mapping = {
    'satilir_photos_1000': 'satilir_properties_1000_with_photos.csv',
    'satilir_photos_1000_2000': 'satilir_properties_1000_2000_with_photos.csv',
    'satilir_photos_2000_3000': 'satilir_properties_2000_3000_with_photos.csv',
    'satilir_photos_3000_4500': 'satilir_properties_3000_4500_with_photos.csv',
    'satilir_photos_4500_5500': 'satilir_properties_4500_5500_with_photos.csv',
    'satilir_photos_5500_end': 'satilir_properties_5500_end_with_photos.csv',
}

all_results = []

# Process each photo folder
for photos_folder, csv_filename in folder_csv_mapping.items():
    photos_dir = base_dir / photos_folder
    csv_path = base_dir / csv_filename
    
    if not photos_dir.exists():
        print(f"⊘ {photos_folder} not found, skipping...")
        continue
    
    if not csv_path.exists():
        print(f"⊘ {csv_filename} not found, skipping...")
        continue
    
    print(f"Processing {photos_folder}...")
    
    # Read CSV
    df = pd.read_csv(csv_path)
    df['price'] = pd.to_numeric(df['price'], errors='coerce')
    
    # Build slug -> price mapping
    df['slug'] = (
        df['link']
        .astype(str)
        .str.strip()
        .str.rstrip('/')
        .str.split('/')
        .str[-1]
    )
    slug_to_price = (
        df[['slug', 'price']]
        .dropna(subset=['slug'])
        .drop_duplicates(subset=['slug'], keep='first')
        .set_index('slug')['price']
    )
    
    # Process subfolders in this photo directory
    folder_count = 0
    for subfolder in sorted(photos_dir.iterdir()):
        if not subfolder.is_dir():
            continue
        
        # Extract ID and slug from folder name
        # Pattern: 001_satilir-..., 0602_satilir-..., etc.
        m = re.match(r'^(\d+)_([^/]+)$', subfolder.name)
        if not m:
            continue
        
        house_id_str, slug = m.groups()
        house_id = int(house_id_str)
        price = slug_to_price.get(slug, pd.NA)
        
        all_results.append({
            'house_id': house_id,
            'price': price,
            'image_folder_name': subfolder.name,
            'source_folder': photos_folder,
        })
        folder_count += 1
    
    print(f"  ✓ Found {folder_count} image folders")

# Create consolidated DataFrame
result_df = pd.DataFrame(all_results).sort_values('house_id').reset_index(drop=True)

# Save
output_path = base_dir / 'satilir_id_price_folder_all.csv'
result_df.to_csv(output_path, index=False)

print(f"\n✓ Created: {output_path}")
print(f"✓ Total rows: {len(result_df)}")
print(f"✓ Price range: {result_df['price'].min()} - {result_df['price'].max()}")
print(f"\nPreview:")
print(result_df.head(15))

⊘ satilir_properties_1000_with_photos.csv not found, skipping...
Processing satilir_photos_1000_2000...
  ✓ Found 1000 image folders
Processing satilir_photos_2000_3000...
  ✓ Found 1001 image folders
Processing satilir_photos_3000_4500...
  ✓ Found 1474 image folders
Processing satilir_photos_4500_5500...
  ✓ Found 995 image folders
Processing satilir_photos_5500_end...
  ✓ Found 798 image folders

✓ Created: /home/admin123/AI_project/satilir_id_price_folder_all.csv
✓ Total rows: 5268
✓ Price range: 7300.0 - 63000000.0

Preview:
    house_id     price                                  image_folder_name  \
0       1001  200000.0  1001_satilir-3-otaqli-yeni-tikili-nerimanov-ra...
1       1002  800000.0  1002_satilir-4-otaqli-yeni-tikili-nerimanov-ra...
2       1003  210000.0  1003_satilir-2-otaqli-yeni-tikili-nerimanov-ra...
3       1004       NaN                    1004_neftcilerde-obyekt-satilir
4       1005  149000.0  1005_satilir-4-otaqli-kohne-tikili-bineqedi-ra...
5       1006   45000.0  1006_satilir-1-otaqli-yeni-tikili-xirdalan-abs...
6       1007  109000.0  1007_satilir-3-otaqli-yeni-tikili-xirdalan-h-e...
7       1008   70500.0  1008_satilir-2-otaqli-yeni-tikili-xirdalan-h-e...
8       1009  290000.0  1009_satilir-2-otaqli-yeni-tikili-nesimi-rayon...
9       1010  135000.0  1010_satilir-3-otaqli-yeni-tikili-xirdalan-h-a...
10      1011   54000.0  1011_satilir-1-otaqli-yeni-tikili-xirdalan-h-e...
11      1012  125000.0  1012_satilir-3-otaqli-heyet-evi-villa-xirdalan...
12      1013   85000.0  1013_satilir-2-otaqli-yeni-tikili-xirdalan-h-e...
13      1014  212000.0  1014_satilir-2-otaqli-yeni-tikili-nizami-rayon...
14      1015  145000.0  1015_satilir-3-otaqli-heyet-evi-villa-xirdalan...

               source_folder
0   satilir_photos_1000_2000
1   satilir_photos_1000_2000
2   satilir_photos_1000_2000
3   satilir_photos_1000_2000
4   satilir_photos_1000_2000
5   satilir_photos_1000_2000
6   satilir_photos_1000_2000
7   satilir_photos_1000_2000
8   satilir_photos_1000_2000
9   satilir_photos_1000_2000
10  satilir_photos_1000_2000
11  satilir_photos_1000_2000
12  satilir_photos_1000_2000
13  satilir_photos_1000_2000
14  satilir_photos_1000_2000

In [34]:
base_dir = Path('/home/admin123/AI_project')
file_path = base_dir / 'satilir_id_price_folder.csv'

df = pd.read_csv(file_path)

In [36]:
df_cleaned = df[df['price'].notna()].copy()

In [38]:
df_cleaned.to_csv(file_path, index=False)